this.j$=this.jStat=function(f,e){function a(d,b){var n=d>b?d:b;return f.pow(10,17-~~(f.log(0<n?n:-n)*f.LOG10E))}function b(d){return"[object Function]"===p.call(d)}function d(d){return"number"===typeof d&&d===d}function n(){return new n._init(arguments)}function l(){return 0}function k(){return 1}function g(d,b){return d===b?1:0}var h=Array.prototype.concat,m=Array.prototype.slice,p=Object.prototype.toString,q=Array.isArray||function(d){return"[object Array]"===p.call(d)};n.fn=n.prototype;n._init=
function(a){var e;if(q(a[0]))if(q(a[0][0])){b(a[1])&&(a[0]=n.map(a[0],a[1]));for(e=0;e<a[0].length;e++)this[e]=a[0][e];this.length=a[0].length}else this[0]=b(a[1])?n.map(a[0],a[1]):a[0],this.length=1;else{if(d(a[0]))this[0]=n.seq.apply(null,a);else{if(a[0]instanceof n)return n(a[0].toArray());this[0]=[]}this.length=1}return this};n._init.prototype=n.prototype;n._init.constructor=n;n.utils={calcRdx:a,isArray:q,isFunction:b,isNumber:d,toVector:function(d){return h.apply([],d)}};n.extend=function(d){var b,
a;if(1===arguments.length){for(a in d)n[a]=d[a];return this}for(b=1;b<arguments.length;b++)for(a in arguments[b])d[a]=arguments[b][a];return d};n.rows=function(d){return d.length||1};n.cols=function(d){return d[0].length||1};n.dimensions=function(d){return{rows:n.rows(d),cols:n.cols(d)}};n.row=function(d,b){return d[b]};n.col=function(d,b){for(var n=Array(d.length),a=0;a<d.length;a++)n[a]=[d[a][b]];return n};n.diag=function(d){for(var b=n.rows(d),a=Array(b),e=0;e<b;e++)a[e]=[d[e][e]];return a};n.antidiag=
function(d){for(var b=n.rows(d)-1,a=Array(b),e=0;0<=b;b--,e++)a[e]=[d[e][b]];return a};n.transpose=function(d){var b=[],a,n,e,l,f;q(d[0])||(d=[d]);n=d.length;e=d[0].length;for(f=0;f<e;f++){a=Array(n);for(l=0;l<n;l++)a[l]=d[l][f];b.push(a)}return 1===b.length?b[0]:b};n.map=function(d,b,a){var n,e,l,f;q(d[0])||(d=[d]);n=d.length;e=d[0].length;l=a?d:Array(n);for(a=0;a<n;a++)for(l[a]||(l[a]=Array(e)),f=0;f<e;f++)l[a][f]=b(d[a][f],a,f);return 1===l.length?l[0]:l};n.cumreduce=function(d,b,a){var n,e,l,
f;q(d[0])||(d=[d]);n=d.length;e=d[0].length;l=a?d:Array(n);for(a=0;a<n;a++)for(l[a]||(l[a]=Array(e)),0<e&&(l[a][0]=d[a][0]),f=1;f<e;f++)l[a][f]=b(l[a][f-1],d[a][f]);return 1===l.length?l[0]:l};n.alter=function(d,b){return n.map(d,b,!0)};n.create=function(d,a,n){var e=Array(d),l,f;b(a)&&(n=a,a=d);for(l=0;l<d;l++)for(e[l]=Array(a),f=0;f<a;f++)e[l][f]=n(l,f);return e};n.zeros=function(b,a){d(a)||(a=b);return n.create(b,a,l)};n.ones=function(b,a){d(a)||(a=b);return n.create(b,a,k)};n.rand=function(b,
a){d(a)||(a=b);return n.create(b,a,f.random)};n.identity=function(b,a){d(a)||(a=b);return n.create(b,a,g)};n.symmetric=function(d){var b=d.length,a,n;if(d.length!==d[0].length)return!1;for(a=0;a<b;a++)for(n=0;n<b;n++)if(d[n][a]!==d[a][n])return!1;return!0};n.clear=function(d){return n.alter(d,l)};n.seq=function(d,n,e,l){b(l)||(l=!1);var f=[],k=a(d,n);e=(n*k-d*k)/((e-1)*k);var g=d,h;for(h=0;g<=n;h++,g=(d*k+e*k*h)/k)f.push(l?l(g,h):g);return f};var r=n.prototype;r.length=0;r.push=Array.prototype.push;
r.sort=Array.prototype.sort;r.splice=Array.prototype.splice;r.slice=Array.prototype.slice;r.toArray=function(){return 1<this.length?m.call(this):m.call(this)[0]};r.map=function(d,b){return n(n.map(this,d,b))};r.cumreduce=function(d,b){return n(n.cumreduce(this,d,b))};r.alter=function(d){n.alter(this,d);return this};(function(d){for(var b=0;b<d.length;b++)(function(d){r[d]=function(b){var a=this,e;if(b)return setTimeout(function(){b.call(a,r[d].call(a))}),this;e=n[d](this);return q(e)?n(e):e}})(d[b])})("transpose clear symmetric rows cols dimensions diag antidiag".split(" "));
(function(d){for(var b=0;b<d.length;b++)(function(d){r[d]=function(b,a){var e=this;return a?(setTimeout(function(){a.call(e,r[d].call(e,b))}),this):n(n[d](this,b))}})(d[b])})(["row","col"]);(function(d){for(var b=0;b<d.length;b++){var a=d[b];r[a]=new Function("return jStat(jStat."+a+".apply(null, arguments));")}})(["create","zeros","ones","rand","identity"]);return n}(Math);
(function(f,e){function a(d,b){return d-b}var b=f.utils.isFunction;f.sum=function(d){for(var b=0,a=d.length;0<=--a;)b+=d[a];return b};f.sumsqrd=function(d){for(var b=0,a=d.length;0<=--a;)b+=d[a]*d[a];return b};f.sumsqerr=function(d){for(var b=f.mean(d),a=0,e=d.length,h;0<=--e;)h=d[e]-b,a+=h*h;return a};f.product=function(d){for(var b=1,a=d.length;0<=--a;)b*=d[a];return b};f.min=function(d){for(var b=d[0],a=0;++a<d.length;)d[a]<b&&(b=d[a]);return b};f.max=function(d){for(var b=d[0],a=0;++a<d.length;)d[a]>
b&&(b=d[a]);return b};f.mean=function(d){return f.sum(d)/d.length};f.meansqerr=function(d){return f.sumsqerr(d)/d.length};f.geomean=function(d){return e.pow(f.product(d),1/d.length)};f.median=function(d){var b=d.length;d=d.slice().sort(a);return b&1?d[b/2|0]:(d[b/2-1]+d[b/2])/2};f.cumsum=function(d){return f.cumreduce(d,function(d,b){return d+b})};f.cumprod=function(d){return f.cumreduce(d,function(d,b){return d*b})};f.diff=function(d){var b=[],a=d.length,e;for(e=1;e<a;e++)b.push(d[e]-d[e-1]);return b};
f.mode=function(d){var b=d.length;d=d.slice().sort(a);var e=1,f=0,h=0,m=[],p;for(p=0;p<b;p++)d[p]===d[p+1]?e++:(e>f?(m=[d[p]],f=e,h=0):e===f&&(m.push(d[p]),h++),e=1);return 0===h?m[0]:m};f.range=function(d){return f.max(d)-f.min(d)};f.variance=function(d,b){return f.sumsqerr(d)/(d.length-(b?1:0))};f.stdev=function(d,b){return e.sqrt(f.variance(d,b))};f.meandev=function(d){var b=0,a=f.mean(d),g;for(g=d.length-1;0<=g;g--)b+=e.abs(d[g]-a);return b/d.length};f.meddev=function(d){var b=0,a=f.median(d),
g;for(g=d.length-1;0<=g;g--)b+=e.abs(d[g]-a);return b/d.length};f.coeffvar=function(d){return f.stdev(d)/f.mean(d)};f.quartiles=function(d){var b=d.length;d=d.slice().sort(a);return[d[e.round(b/4)-1],d[e.round(b/2)-1],d[e.round(3*b/4)-1]]};f.quantiles=function(d,b,f,g){var h=d.slice().sort(a),m=[b.length];d=d.length;var p,q,r;"undefined"===typeof f&&(f=.375);"undefined"===typeof g&&(g=.375);for(p=0;p<b.length;p++)q=b[p],r=f+q*(1-f-g),r=d*q+r,q=e.floor(e.max(1,e.min(r,d-1))),r=e.max(0,e.min(r-q,1)),
m[p]=(1-r)*h[q-1]+r*h[q];return m};f.percentileOfScore=function(d,b,a){var e=0,f=d.length,m=!1,p;"strict"===a&&(m=!0);for(p=0;p<f;p++)a=d[p],(m&&a<b||!m&&a<=b)&&e++;return e/f};f.histogram=function(d,b){var a=f.min(d),g=b||4,h=(f.max(d)-a)/g,m=d.length;b=[];var p;for(p=0;p<g;p++)b[p]=0;for(p=0;p<m;p++)b[e.min(e.floor((d[p]-a)/h),g-1)]+=1;return b};f.covariance=function(d,b){var a=f.mean(d),e=f.mean(b),h=d.length,m=Array(h),p;for(p=0;p<h;p++)m[p]=(d[p]-a)*(b[p]-e);return f.sum(m)/(h-1)};f.corrcoeff=
function(d,b){return f.covariance(d,b)/f.stdev(d,1)/f.stdev(b,1)};f.stanMoment=function(d,b){var a=f.mean(d),g=f.stdev(d),h=d.length,m=0;for(i=0;i<h;i++)m+=e.pow((d[i]-a)/g,b);return m/d.length};f.skewness=function(d){return f.stanMoment(d,3)};f.kurtosis=function(d){return f.stanMoment(d,4)-3};var d=f.prototype;(function(a){for(var e=0;e<a.length;e++)(function(a){d[a]=function(n,e){var l=[],p=0,q=this;b(n)&&(e=n,n=!1);if(e)return setTimeout(function(){e.call(q,d[a].call(q,n))}),this;if(1<this.length){for(q=
!0===n?this:this.transpose();p<q.length;p++)l[p]=f[a](q[p]);return l}return f[a](this[0],n)}})(a[e])})(["cumsum","cumprod"]);(function(a){for(var e=0;e<a.length;e++)(function(a){d[a]=function(e,n){var l=[],p=0,q=this;b(e)&&(n=e,e=!1);if(n)return setTimeout(function(){n.call(q,d[a].call(q,e))}),this;if(1<this.length){for(q=!0===e?this:this.transpose();p<q.length;p++)l[p]=f[a](q[p]);return!0===e?f[a](f.utils.toVector(l)):l}return f[a](this[0],e)}})(a[e])})("sum sumsqrd sumsqerr product min max mean meansqerr geomean median diff mode range variance stdev meandev meddev coeffvar quartiles histogram skewness kurtosis".split(" "));
(function(a){for(var e=0;e<a.length;e++)(function(a){d[a]=function(){var e=[],n=0,l=this,p=Array.prototype.slice.call(arguments);if(b(p[p.length-1])){var q=p[p.length-1],r=p.slice(0,p.length-1);setTimeout(function(){q.call(l,d[a].apply(l,r))});return this}q=void 0;if(1<this.length){for(l=l.transpose();n<l.length;n++)e[n]=f[a].apply(l,[l[n]].concat(p));return e}return f[a].apply(l,[this[0]].concat(p))}})(a[e])})(["quantiles","percentileOfScore"])})(this.jStat,Math);
(function(f,e){f.gammaln=function(a){var b=0,d=[76.18009172947146,-86.50532032941678,24.01409824083091,-1.231739572450155,.001208650973866179,-5.395239384953E-6],n=1.000000000190015,f,k;k=(f=a)+5.5;for(k-=(a+.5)*e.log(k);6>b;b++)n+=d[b]/++f;return e.log(2.5066282746310007*n/a)-k};f.gammafn=function(a){var b=[-1.716185138865495,24.76565080557592,-379.80425647094563,629.3311553128184,866.9662027904133,-31451.272968848367,-36144.413418691176,66456.14382024054],d=[-30.8402300119739,315.35062697960416,
-1015.1563674902192,-3107.771671572311,22538.11842098015,4755.846277527881,-134659.9598649693,-115132.2596755535],n=!1,f=0,k=0,g=0,h,m,p;if(0>=a)if(m=a%1+3.6E-16)n=(a&1?-1:1)*e.PI/e.sin(e.PI*m),a=1-a;else return Infinity;p=a;m=1>a?a++:(a-=f=(a|0)-1)-1;for(h=0;8>h;++h)g=(g+b[h])*m,k=k*m+d[h];m=g/k+1;if(p<a)m/=p;else if(p>a)for(h=0;h<f;++h)m*=a,a++;n&&(m=n/m);return m};f.gammap=function(a,b){return f.lowRegGamma(a,b)*f.gammafn(a)};f.lowRegGamma=function(a,b){var d=f.gammaln(a),n=a,l=1/a,k=l,g=b+1-a,
h=1/1E-30,m=1/g,p=m,q=1,r=-~(8.5*e.log(1<=a?a:1/a)+.4*a+17);if(0>b||0>=a)return NaN;if(b<a+1){for(;q<=r;q++)l+=k*=b/++n;return l*e.exp(-b+a*e.log(b)-d)}for(;q<=r;q++)n=-q*(q-a),g+=2,m=n*m+g,h=g+n/h,m=1/m,p=p*m*h;return 1-p*e.exp(-b+a*e.log(b)-d)};f.factorialln=function(a){return 0>a?NaN:f.gammaln(a+1)};f.factorial=function(a){return 0>a?NaN:f.gammafn(a+1)};f.combination=function(a,b){return 170<a||170<b?e.exp(f.combinationln(a,b)):f.factorial(a)/f.factorial(b)/f.factorial(a-b)};f.combinationln=function(a,
b){return f.factorialln(a)-f.factorialln(b)-f.factorialln(a-b)};f.permutation=function(a,b){return f.factorial(a)/f.factorial(a-b)};f.betafn=function(a,b){return 0>=a||0>=b?void 0:170<a+b?e.exp(f.betaln(a,b)):f.gammafn(a)*f.gammafn(b)/f.gammafn(a+b)};f.betaln=function(a,b){return f.gammaln(a)+f.gammaln(b)-f.gammaln(a+b)};f.betacf=function(a,b,d){var n=1,f=b+d,k=b+1,g=b-1,h=1,m=1-f*a/k,p,q,r;1E-30>e.abs(m)&&(m=1E-30);for(r=m=1/m;100>=n&&!(p=2*n,q=n*(d-n)*a/((g+p)*(b+p)),m=1+q*m,1E-30>e.abs(m)&&(m=
1E-30),h=1+q/h,1E-30>e.abs(h)&&(h=1E-30),m=1/m,r=r*m*h,q=-(b+n)*(f+n)*a/((b+p)*(k+p)),m=1+q*m,1E-30>e.abs(m)&&(m=1E-30),h=1+q/h,1E-30>e.abs(h)&&(h=1E-30),m=1/m,p=m*h,r*=p,3E-7>e.abs(p-1));n++);return r};f.gammapinv=function(a,b){var d=0,n=b-1,l=f.gammaln(b),k,g,h,m,p;if(1<=a)return e.max(100,b+100*e.sqrt(b));if(0>=a)return 0;1<b?(m=e.log(n),p=e.exp(n*(m-1)-l),h=e.sqrt(-2*e.log(.5>a?a:1-a)),k=(2.30753+.27061*h)/(1+h*(.99229+.04481*h))-h,.5>a&&(k=-k),k=e.max(.001,b*e.pow(1-1/(9*b)-k/(3*e.sqrt(b)),3))):
(h=1-b*(.253+.12*b),k=a<h?e.pow(a/h,1/b):1-e.log(1-(a-h)/(1-h)));for(;12>d;d++){if(0>=k)return 0;g=f.lowRegGamma(b,k)-a;h=1<b?p*e.exp(-(k-n)+n*(e.log(k)-m)):e.exp(-k+n*e.log(k)-l);g/=h;k-=h=g/(1-.5*e.min(1,g*((b-1)/k-1)));0>=k&&(k=.5*(k+h));if(e.abs(h)<1E-8*k)break}return k};f.erf=function(a){var b=[-1.3026537197817094,.6419697923564902,.019476473204185836,-.00956151478680863,-9.46595344482036E-4,3.66839497852761E-4,4.2523324806907E-5,-2.0278578112534E-5,-1.624290004647E-6,1.30365583558E-6,1.5626441722E-8,
-8.5238095915E-8,6.529054439E-9,5.059343495E-9,-9.91364156E-10,-2.27365122E-10,9.6467911E-11,2.394038E-12,-6.886027E-12,8.94487E-13,3.13092E-13,-1.12708E-13,3.81E-16,7.106E-15,-1.523E-15,-9.4E-17,1.21E-16,-2.8E-17],d=b.length-1,n=!1,f=0,k=0,g,h,m;0>a&&(a=-a,n=!0);g=2/(2+a);for(h=4*g-2;0<d;d--)m=f,f=h*f-k+b[d],k=m;a=g*e.exp(-a*a+.5*(b[0]+h*f)-k);return n?a-1:1-a};f.erfc=function(a){return 1-f.erf(a)};f.erfcinv=function(a){var b=0,d,n,l;if(2<=a)return-100;if(0>=a)return 100;l=1>a?a:2-a;d=e.sqrt(-2*
e.log(l/2));for(d=-.70711*((2.30753+.27061*d)/(1+d*(.99229+.04481*d))-d);2>b;b++)n=f.erfc(d)-l,d+=n/(1.1283791670955126*e.exp(-d*d)-d*n);return 1>a?d:-d};f.ibetainv=function(a,b,d){var n=b-1,l=d-1,k=0,g,h,m,p;if(0>=a)return 0;if(1<=a)return 1;1<=b&&1<=d?(g=e.sqrt(-2*e.log(.5>a?a:1-a)),h=(2.30753+.27061*g)/(1+g*(.99229+.04481*g))-g,.5>a&&(h=-h),g=(h*h-3)/6,p=2/(1/(2*b-1)+1/(2*d-1)),h=h*e.sqrt(g+p)/p-(1/(2*d-1)-1/(2*b-1))*(g+5/6-2/(3*p)),h=b/(b+d*e.exp(2*h))):(g=e.log(b/(b+d)),h=e.log(d/(b+d)),g=e.exp(b*
g)/b,m=e.exp(d*h)/d,h=g+m,h=a<g/h?e.pow(b*h*a,1/b):1-e.pow(d*h*(1-a),1/d));for(p=-f.gammaln(b)-f.gammaln(d)+f.gammaln(b+d);10>k&&0!==h&&1!==h&&!(m=f.ibeta(h,b,d)-a,g=e.exp(n*e.log(h)+l*e.log(1-h)+p),m/=g,h-=g=m/(1-.5*e.min(1,m*(n/h-l/(1-h)))),0>=h&&(h=.5*(h+g)),1<=h&&(h=.5*(h+g+1)),e.abs(g)<1E-8*h&&0<k);k++);return h};f.ibeta=function(a,b,d){var n=0===a||1===a?0:e.exp(f.gammaln(b+d)-f.gammaln(b)-f.gammaln(d)+b*e.log(a)+d*e.log(1-a));return 0>a||1<a?!1:a<(b+1)/(b+d+2)?n*f.betacf(a,b,d)/b:1-n*f.betacf(1-
a,d,b)/d};f.randn=function(a,b){var d,n,l,k;b||(b=a);if(a)return f.create(a,b,function(){return f.randn()});do d=e.random(),n=1.7156*(e.random()-.5),l=d-.449871,k=e.abs(n)+.386595,l=l*l+k*(.196*k-.25472*l);while(.27597<l&&(.27846<l||n*n>-4*e.log(d)*d*d));return n/d};f.randg=function(a,b,d){var n=a,l,k,g;d||(d=b);a||(a=1);if(b)return n=f.zeros(b,d),n.alter(function(){return f.randg(a)}),n;1>a&&(a+=1);b=a-1/3;d=1/e.sqrt(9*b);do{do g=f.randn(),k=1+d*g;while(0>=k);k*=k*k;l=e.random()}while(l>1-.331*e.pow(g,
4)&&e.log(l)>.5*g*g+b*(1-k+e.log(k)));if(a==n)return b*k;do l=e.random();while(0===l);return e.pow(l,1/n)*b*k};(function(a){for(var b=0;b<a.length;b++)(function(d){f.fn[d]=function(){return f(f.map(this,function(b){return f[d](b)}))}})(a[b])})(["gammaln","gammafn","factorial","factorialln"]);(function(a){for(var b=0;b<a.length;b++)(function(d){f.fn[d]=function(){return f(f[d].apply(null,arguments))}})(a[b])})(["randn"])})(this.jStat,Math);
(function(f,e){(function(a){for(var b=0;b<a.length;b++)(function(d){f[d]=function(d,b,a){if(!(this instanceof arguments.callee))return new arguments.callee(d,b,a);this._a=d;this._b=b;this._c=a;return this};f.fn[d]=function(b,a,e){b=f[d](b,a,e);b.data=this;return b};f[d].prototype.sample=function(b){var a=this._a,e=this._b,g=this._c;return b?f.alter(b,function(){return f[d].sample(a,e,g)}):f[d].sample(a,e,g)};(function(b){for(var a=0;a<b.length;a++)(function(b){f[d].prototype[b]=function(a){var e=
this._a,n=this._b,l=this._c;a||0===a||(a=this.data);return"number"!==typeof a?f.fn.map.call(a,function(a){return f[d][b](a,e,n,l)}):f[d][b](a,e,n,l)}})(b[a])})(["pdf","cdf","inv"]);(function(b){for(var a=0;a<b.length;a++)(function(b){f[d].prototype[b]=function(){return f[d][b](this._a,this._b,this._c)}})(b[a])})(["mean","median","mode","variance"])})(a[b])})("beta centralF cauchy chisquare exponential gamma invgamma kumaraswamy lognormal normal pareto studentt weibull uniform  binomial negbin hypgeom poisson triangular".split(" "));
f.extend(f.beta,{pdf:function(a,b,d){return 1<a||0>a?0:1==b&&1==d?1:512>b||512>d?e.pow(a,b-1)*e.pow(1-a,d-1)/f.betafn(b,d):e.exp((b-1)*e.log(a)+(d-1)*e.log(1-a)-f.betaln(b,d))},cdf:function(a,b,d){return 1<a||0>a?1*(1<a):f.ibeta(a,b,d)},inv:function(a,b,d){return f.ibetainv(a,b,d)},mean:function(a,b){return a/(a+b)},median:function(a,b){throw Error("median not yet implemented");},mode:function(a,b){return a*b/(e.pow(a+b,2)*(a+b+1))},sample:function(a,b){var d=f.randg(a);return d/(d+f.randg(b))},variance:function(a,
b){return a*b/(e.pow(a+b,2)*(a+b+1))}});f.extend(f.centralF,{pdf:function(a,b,d){if(!(0>a))return 2>=b?1===b&&1===d?Infinity:2===b&&1===d?1:e.sqrt(e.pow(b*a,b)*e.pow(d,d)/e.pow(b*a+d,b+d))/(a*f.betafn(b/2,d/2)):d/(d+a*b)*b/2*f.binomial.pdf((b-2)/2,(b+d-2)/2,b*a/(d+a*b))},cdf:function(a,b,d){return f.ibeta(b*a/(b*a+d),b/2,d/2)},inv:function(a,b,d){return d/(b*(1/f.ibetainv(a,b/2,d/2)-1))},mean:function(a,b){return 2<b?b/(b-2):void 0},mode:function(a,b){return 2<a?b*(a-2)/(a*(b+2)):void 0},sample:function(a,
b){var d=2*f.randg(a/2),e=2*f.randg(b/2);return d/a/(e/b)},variance:function(a,b){return 4>=b?void 0:2*b*b*(a+b-2)/(a*(b-2)*(b-2)*(b-4))}});f.extend(f.cauchy,{pdf:function(a,b,d){return d/(e.pow(a-b,2)+e.pow(d,2))/e.PI},cdf:function(a,b,d){return e.atan((a-b)/d)/e.PI+.5},inv:function(a,b,d){return b+d*e.tan(e.PI*(a-.5))},median:function(a,b){return a},mode:function(a,b){return a},sample:function(a,b){return f.randn()*e.sqrt(1/(2*f.randg(.5)))*b+a}});f.extend(f.chisquare,{pdf:function(a,b){return 0===
a?0:e.exp((b/2-1)*e.log(a)-a/2-b/2*e.log(2)-f.gammaln(b/2))},cdf:function(a,b){return f.lowRegGamma(b/2,a/2)},inv:function(a,b){return 2*f.gammapinv(a,.5*b)},mean:function(a){return a},median:function(a){return a*e.pow(1-2/(9*a),3)},mode:function(a){return 0<a-2?a-2:0},sample:function(a){return 2*f.randg(a/2)},variance:function(a){return 2*a}});f.extend(f.exponential,{pdf:function(a,b){return 0>a?0:b*e.exp(-b*a)},cdf:function(a,b){return 0>a?0:1-e.exp(-b*a)},inv:function(a,b){return-e.log(1-a)/b},
mean:function(a){return 1/a},median:function(a){return 1/a*e.log(2)},mode:function(a){return 0},sample:function(a){return-1/a*e.log(e.random())},variance:function(a){return e.pow(a,-2)}});f.extend(f.gamma,{pdf:function(a,b,d){return e.exp((b-1)*e.log(a)-a/d-f.gammaln(b)-b*e.log(d))},cdf:function(a,b,d){return f.lowRegGamma(b,a/d)},inv:function(a,b,d){return f.gammapinv(a,b)*d},mean:function(a,b){return a*b},mode:function(a,b){if(1<a)return(a-1)*b},sample:function(a,b){return f.randg(a)*b},variance:function(a,
b){return a*b*b}});f.extend(f.invgamma,{pdf:function(a,b,d){return e.exp(-(b+1)*e.log(a)-d/a-f.gammaln(b)+b*e.log(d))},cdf:function(a,b,d){return 1-f.lowRegGamma(b,d/a)},inv:function(a,b,d){return d/f.gammapinv(1-a,b)},mean:function(a,b){return 1<a?b/(a-1):void 0},mode:function(a,b){return b/(a+1)},sample:function(a,b){return b/f.randg(a)},variance:function(a,b){return 2>=a?void 0:b*b/((a-1)*(a-1)*(a-2))}});f.extend(f.kumaraswamy,{pdf:function(a,b,d){return e.exp(e.log(b)+e.log(d)+(b-1)*e.log(a)+
(d-1)*e.log(1-e.pow(a,b)))},cdf:function(a,b,d){return 1-e.pow(1-e.pow(a,b),d)},mean:function(a,b){return b*f.gammafn(1+1/a)*f.gammafn(b)/f.gammafn(1+1/a+b)},median:function(a,b){return e.pow(1-e.pow(2,-1/b),1/a)},mode:function(a,b){return 1<=a&&1<=b&&1!==a&&1!==b?e.pow((a-1)/(a*b-1),1/a):void 0},variance:function(a,b){throw Error("variance not yet implemented");}});f.extend(f.lognormal,{pdf:function(a,b,d){return e.exp(-e.log(a)-.5*e.log(2*e.PI)-e.log(d)-e.pow(e.log(a)-b,2)/(2*d*d))},cdf:function(a,
b,d){return.5+.5*f.erf((e.log(a)-b)/e.sqrt(2*d*d))},inv:function(a,b,d){return e.exp(-1.4142135623730951*d*f.erfcinv(2*a)+b)},mean:function(a,b){return e.exp(a+b*b/2)},median:function(a,b){return e.exp(a)},mode:function(a,b){return e.exp(a-b*b)},sample:function(a,b){return e.exp(f.randn()*b+a)},variance:function(a,b){return(e.exp(b*b)-1)*e.exp(2*a+b*b)}});f.extend(f.normal,{pdf:function(a,b,d){return e.exp(-.5*e.log(2*e.PI)-e.log(d)-e.pow(a-b,2)/(2*d*d))},cdf:function(a,b,d){return.5*(1+f.erf((a-
b)/e.sqrt(2*d*d)))},inv:function(a,b,d){return-1.4142135623730951*d*f.erfcinv(2*a)+b},mean:function(a,b){return a},median:function(a,b){return a},mode:function(a,b){return a},sample:function(a,b){return f.randn()*b+a},variance:function(a,b){return b*b}});f.extend(f.pareto,{pdf:function(a,b,d){return a<b?void 0:d*e.pow(b,d)/e.pow(a,d+1)},cdf:function(a,b,d){return 1-e.pow(b/a,d)},mean:function(a,b){return 1>=b?void 0:b*e.pow(a,b)/(b-1)},median:function(a,b){return a*b*e.SQRT2},mode:function(a,b){return a},
variance:function(a,b){return 2>=b?void 0:a*a*b/(e.pow(b-1,2)*(b-2))}});f.extend(f.studentt,{pdf:function(a,b){return f.gammafn((b+1)/2)/(e.sqrt(b*e.PI)*f.gammafn(b/2))*e.pow(1+a*a/b,-((b+1)/2))},cdf:function(a,b){var d=b/2;return f.ibeta((a+e.sqrt(a*a+b))/(2*e.sqrt(a*a+b)),d,d)},inv:function(a,b){var d=f.ibetainv(2*e.min(a,1-a),.5*b,.5),d=e.sqrt(b*(1-d)/d);return.5<a?d:-d},mean:function(a){return 1<a?0:void 0},median:function(a){return 0},mode:function(a){return 0},sample:function(a){return f.randn()*
e.sqrt(a/(2*f.randg(a/2)))},variance:function(a){return 2<a?a/(a-2):1<a?Infinity:void 0}});f.extend(f.weibull,{pdf:function(a,b,d){return 0>a?0:d/b*e.pow(a/b,d-1)*e.exp(-e.pow(a/b,d))},cdf:function(a,b,d){return 0>a?0:1-e.exp(-e.pow(a/b,d))},inv:function(a,b,d){return b*e.pow(-e.log(1-a),1/d)},mean:function(a,b){return a*f.gammafn(1+1/b)},median:function(a,b){return a*e.pow(e.log(2),1/b)},mode:function(a,b){return 1>=b?void 0:a*e.pow((b-1)/b,1/b)},sample:function(a,b){return a*e.pow(-e.log(e.random()),
1/b)},variance:function(a,b){return a*a*f.gammafn(1+2/b)-e.pow(this.mean(a,b),2)}});f.extend(f.uniform,{pdf:function(a,b,d){return a<b||a>d?0:1/(d-b)},cdf:function(a,b,d){return a<b?0:a<d?(a-b)/(d-b):1},inv:function(a,b,d){return b+a*(d-b)},mean:function(a,b){return.5*(a+b)},median:function(a,b){return f.mean(a,b)},mode:function(a,b){throw Error("mode is not yet implemented");},sample:function(a,b){return a/2+b/2+(b/2-a/2)*(2*e.random()-1)},variance:function(a,b){return e.pow(b-a,2)/12}});f.extend(f.binomial,
{pdf:function(a,b,d){return 0===d||1===d?b*d===a?1:0:f.combination(b,a)*e.pow(d,a)*e.pow(1-d,b-a)},cdf:function(a,b,d){var e=[],l=0;if(0>a)return 0;if(a<b){for(;l<=a;l++)e[l]=f.binomial.pdf(l,b,d);return f.sum(e)}return 1}});f.extend(f.negbin,{pdf:function(a,b,d){return a!==a|0?!1:0>a?0:f.combination(a+b-1,b-1)*e.pow(1-d,a)*e.pow(d,b)},cdf:function(a,b,d){var e=0,l=0;if(0>a)return 0;for(;l<=a;l++)e+=f.negbin.pdf(l,b,d);return e}});f.extend(f.hypgeom,{pdf:function(a,b,d,n){if(a!==a|0)return!1;if(0>
a||a<d-(b-n)||a>n||a>d)return 0;if(2*d>b)return 2*n>b?f.hypgeom.pdf(b-d-n+a,b,b-d,b-n):f.hypgeom.pdf(n-a,b,b-d,n);if(2*n>b)return f.hypgeom.pdf(d-a,b,d,b-n);if(d<n)return f.hypgeom.pdf(a,b,n,d);for(var l=1,k=0,g=0;g<a;g++){for(;1<l&&k<n;)l*=1-d/(b-k),k++;l*=(n-g)*(d-g)/((g+1)*(b-d-n+g+1))}for(;k<n;k++)l*=1-d/(b-k);return e.min(1,e.max(0,l))},cdf:function(a,b,d,n){if(0>a||a<d-(b-n))return 0;if(a>=n||a>=d)return 1;if(2*d>b)return 2*n>b?f.hypgeom.cdf(b-d-n+a,b,b-d,b-n):1-f.hypgeom.cdf(n-a-1,b,b-d,n);
if(2*n>b)return 1-f.hypgeom.cdf(d-a-1,b,d,b-n);if(d<n)return f.hypgeom.cdf(a,b,n,d);for(var l=1,k=1,g=0,h=0;h<a;h++){for(;1<l&&g<n;){var m=1-d/(b-g),k=k*m,l=l*m;g++}k*=(n-h)*(d-h)/((h+1)*(b-d-n+h+1));l+=k}for(;g<n;g++)l*=1-d/(b-g);return e.min(1,e.max(0,l))}});f.extend(f.poisson,{pdf:function(a,b){return e.pow(b,a)*e.exp(-b)/f.factorial(a)},cdf:function(a,b){var d=[],e=0;if(0>a)return 0;for(;e<=a;e++)d.push(f.poisson.pdf(e,b));return f.sum(d)},mean:function(a){return a},variance:function(a){return a},
sample:function(a){var b=1,d=0;a=e.exp(-a);do d++,b*=e.random();while(b>a);return d-1}});f.extend(f.triangular,{pdf:function(a,b,d,e){return d<=b||e<b||e>d?void 0:a<b||a>d?0:a<=e?e===b?1:2*(a-b)/((d-b)*(e-b)):e===d?1:2*(d-a)/((d-b)*(d-e))},cdf:function(a,b,d,n){return d<=b||n<b||n>d?void 0:a<b?0:a<=n?e.pow(a-b,2)/((d-b)*(n-b)):1-e.pow(d-a,2)/((d-b)*(d-n))},mean:function(a,b,d){return(a+b+d)/3},median:function(a,b,d){if(d<=(a+b)/2)return b-e.sqrt((b-a)*(b-d))/e.sqrt(2);if(d>(a+b)/2)return a+e.sqrt((b-
a)*(d-a))/e.sqrt(2)},mode:function(a,b,d){return d},sample:function(a,b,d){var n=e.random();return n<(d-a)/(b-a)?a+e.sqrt(n*(b-a)*(d-a)):b-e.sqrt((1-n)*(b-a)*(b-d))},variance:function(a,b,d){return(a*a+b*b+d*d-a*b-a*d-b*d)/18}})})(this.jStat,Math);
(function(f,e){var a=Array.prototype.push,b=f.utils.isArray;f.extend({add:function(d,a){return b(a)?(b(a[0])||(a=[a]),f.map(d,function(d,b,e){return d+a[b][e]})):f.map(d,function(d){return d+a})},subtract:function(d,a){return b(a)?(b(a[0])||(a=[a]),f.map(d,function(d,b,e){return d-a[b][e]||0})):f.map(d,function(d){return d-a})},divide:function(d,a){return b(a)?(b(a[0])||(a=[a]),f.multiply(d,f.inv(a))):f.map(d,function(d){return d/a})},multiply:function(d,a){var e,k,g,h,m=d.length,p=d[0].length,q=
f.zeros(m,g=b(a)?a[0].length:p),r=0;if(b(a)){for(;r<g;r++)for(e=0;e<m;e++){for(k=h=0;k<p;k++)h+=d[e][k]*a[k][r];q[e][r]=h}return 1===m&&1===r?q[0][0]:q}return f.map(d,function(d){return d*a})},dot:function(d,a){b(d[0])||(d=[d]);b(a[0])||(a=[a]);for(var e=1===d[0].length&&1!==d.length?f.transpose(d):d,k=1===a[0].length&&1!==a.length?f.transpose(a):a,g=[],h=0,m=e.length,p=e[0].length,q,r;h<m;h++){g[h]=[];for(r=q=0;r<p;r++)q+=e[h][r]*k[h][r];g[h]=q}return 1===g.length?g[0]:g},pow:function(d,b){return f.map(d,
function(d){return e.pow(d,b)})},exp:function(d){return f.map(d,function(d){return e.exp(d)})},log:function(d){return f.map(d,function(d){return e.log(d)})},abs:function(d){return f.map(d,function(d){return e.abs(d)})},norm:function(d,a){var f=0,k=0;isNaN(a)&&(a=2);for(b(d[0])&&(d=d[0]);k<d.length;k++)f+=e.pow(e.abs(d[k]),a);return e.pow(f,1/a)},angle:function(d,a){return e.acos(f.dot(d,a)/(f.norm(d)*f.norm(a)))},aug:function(d,b){for(var e=d.slice(),f=0;f<e.length;f++)a.apply(e[f],b[f]);return e},
inv:function(d){var a=d.length,b=d[0].length,e=f.identity(a,b);d=f.gauss_jordan(d,e);for(var e=[],g=0,h;g<a;g++)for(e[g]=[],h=b;h<d[0].length;h++)e[g][h-b]=d[g][h];return e},det:function(d){var a=d.length,b=2*a,e=Array(b),f=a-1,h=b-1,m=f-a+1,p=h,q=0,r=0,t;if(2===a)return d[0][0]*d[1][1]-d[0][1]*d[1][0];for(;q<b;q++)e[q]=1;for(q=0;q<a;q++){for(t=0;t<a;t++)e[0>m?m+a:m]*=d[q][t],e[p<a?p+a:p]*=d[q][t],m++,p--;m=--f-a+1;p=--h}for(q=0;q<a;q++)r+=e[q];for(;q<b;q++)r-=e[q];return r},gauss_elimination:function(d,
a){var b=0,k=0,g=d.length,h=d[0].length,m=1,p=0,q=[],r;d=f.aug(d,a);r=d[0].length;for(b=0;b<g;b++){m=d[b][b];k=b;for(p=b+1;p<h;p++)m<e.abs(d[p][b])&&(m=d[p][b],k=p);if(k!=b)for(p=0;p<r;p++)m=d[b][p],d[b][p]=d[k][p],d[k][p]=m;for(k=b+1;k<g;k++)for(m=d[k][b]/d[b][b],p=b;p<r;p++)d[k][p]-=m*d[b][p]}for(b=g-1;0<=b;b--){p=0;for(k=b+1;k<=g-1;k++)p+=q[k]*d[b][k];q[b]=(d[b][r-1]-p)/d[b][b]}return q},gauss_jordan:function(d,b){for(var a=f.aug(d,b),k=a.length,g=a[0].length,h=0;h<k;h++){for(var m=h,p=h+1;p<k;p++)e.abs(a[p][h])>
e.abs(a[m][h])&&(m=p);p=a[h];a[h]=a[m];a[m]=p;for(p=h+1;p<k;p++)for(c=a[p][h]/a[h][h],m=h;m<g;m++)a[p][m]-=a[h][m]*c}for(h=k-1;0<=h;h--){c=a[h][h];for(p=0;p<h;p++)for(m=g-1;m>h-1;m--)a[p][m]-=a[h][m]*a[p][h]/c;a[h][h]/=c;for(m=k;m<g;m++)a[h][m]/=c}return a},lu:function(d,a){throw Error("lu not yet implemented");},cholesky:function(d,a){throw Error("cholesky not yet implemented");},gauss_jacobi:function(d,a,b,k){for(var g=0,h=0,m=d.length,p=[],q=[],r=[];g<m;g++)for(p[g]=[],q[g]=[],r[g]=[],h=0;h<m;h++)g>
h?(p[g][h]=d[g][h],q[g][h]=r[g][h]=0):g<h?(q[g][h]=d[g][h],p[g][h]=r[g][h]=0):(r[g][h]=d[g][h],p[g][h]=q[g][h]=0);d=f.multiply(f.multiply(f.inv(r),f.add(p,q)),-1);r=f.multiply(f.inv(r),a);a=b;b=f.add(f.multiply(d,b),r);for(g=2;e.abs(f.norm(f.subtract(b,a)))>k;)a=b,b=f.add(f.multiply(d,a),r),g++;return b},gauss_seidel:function(d,a,b,k){for(var g=0,h=d.length,m=[],p=[],q=[],r;g<h;g++)for(m[g]=[],p[g]=[],q[g]=[],r=0;r<h;r++)g>r?(m[g][r]=d[g][r],p[g][r]=q[g][r]=0):g<r?(p[g][r]=d[g][r],m[g][r]=q[g][r]=
0):(q[g][r]=d[g][r],m[g][r]=p[g][r]=0);d=f.multiply(f.multiply(f.inv(f.add(q,m)),p),-1);m=f.multiply(f.inv(f.add(q,m)),a);a=b;b=f.add(f.multiply(d,b),m);for(g=2;e.abs(f.norm(f.subtract(b,a)))>k;)a=b,b=f.add(f.multiply(d,a),m),g+=1;return b},SOR:function(d,a,b,k,g){for(var h=0,m=d.length,p=[],q=[],r=[],t;h<m;h++)for(p[h]=[],q[h]=[],r[h]=[],t=0;t<m;t++)h>t?(p[h][t]=d[h][t],q[h][t]=r[h][t]=0):h<t?(q[h][t]=d[h][t],p[h][t]=r[h][t]=0):(r[h][t]=d[h][t],p[h][t]=q[h][t]=0);d=f.multiply(f.inv(f.add(r,f.multiply(p,
g))),f.subtract(f.multiply(r,1-g),f.multiply(q,g)));g=f.multiply(f.multiply(f.inv(f.add(r,f.multiply(p,g))),a),g);a=b;b=f.add(f.multiply(d,b),g);for(h=2;e.abs(f.norm(f.subtract(b,a)))>k;)a=b,b=f.add(f.multiply(d,a),g),h++;return b},householder:function(d){for(var a=d.length,b=d[0].length,k=0,g=[],h=[],m;k<a-1;k++){h=0;for(g=k+1;g<b;g++)h+=d[g][k]*d[g][k];g=0<d[k+1][k]?-1:1;h=g*e.sqrt(h);m=e.sqrt((h*h-d[k+1][k]*h)/2);g=f.zeros(a,1);g[k+1][0]=(d[k+1][k]-h)/(2*m);for(h=k+2;h<a;h++)g[h][0]=d[h][k]/(2*
m);h=f.subtract(f.identity(a,b),f.multiply(f.multiply(g,f.transpose(g)),2));d=f.multiply(h,f.multiply(d,h))}return d},QR:function(d,a){for(var b=d.length,k=d[0].length,g=0,h=[],m=[],p=[],q;g<b-1;g++){m=0;for(h=g+1;h<k;h++)m+=d[h][g]*d[h][g];h=0<d[g+1][g]?-1:1;m=h*e.sqrt(m);q=e.sqrt((m*m-d[g+1][g]*m)/2);h=f.zeros(b,1);h[g+1][0]=(d[g+1][g]-m)/(2*q);for(m=g+2;m<b;m++)h[m][0]=d[m][g]/(2*q);m=f.subtract(f.identity(b,k),f.multiply(f.multiply(h,f.transpose(h)),2));d=f.multiply(m,d);a=f.multiply(m,a)}for(g=
b-1;0<=g;g--){for(h=g+1;h<=k-1;h++);p[g]=a[g][0]/d[g][g]}return p},jacobi:function(d){for(var a=1,b=0,k=d.length,g=f.identity(k,k),h=[],m,p,q,r;1===a;){b++;r=d[0][1];a=0;q=1;for(m=0;m<k;m++)for(p=0;p<k;p++)m!=p&&r<e.abs(d[m][p])&&(r=e.abs(d[m][p]),a=m,q=p);m=d[a][a]===d[q][q]?0<d[a][q]?e.PI/4:-e.PI/4:e.atan(2*d[a][q]/(d[a][a]-d[q][q]))/2;p=f.identity(k,k);p[a][a]=e.cos(m);p[a][q]=-e.sin(m);p[q][a]=e.sin(m);p[q][q]=e.cos(m);g=f.multiply(g,p);d=f.multiply(f.multiply(f.inv(p),d),p);a=0;for(m=1;m<k;m++)for(p=
1;p<k;p++)m!=p&&.001<e.abs(d[m][p])&&(a=1)}for(m=0;m<k;m++)h.push(d[m][m]);return[g,h]},rungekutta:function(d,a,b,e,f,h){var m,p,q;if(2===h)for(;e<=b;)m=a*d(e,f),p=a*d(e+a,f+m),f+=(m+p)/2,e+=a;if(4===h)for(;e<=b;)m=a*d(e,f),p=a*d(e+a/2,f+m/2),h=a*d(e+a/2,f+p/2),q=a*d(e+a,f+h),f+=(m+2*p+2*h+q)/6,e+=a;return f},romberg:function(d,a,b,f){for(var g=0,h=(b-a)/2,m=[],p=[],q=[],r,t,v;g<f/2;){v=d(a);t=a;for(r=0;t<=b;t+=h,r++)m[r]=t;r=m.length;for(t=1;t<r-1;t++)v+=(0!==t%2?4:2)*d(m[t]);v=h/3*(v+d(b));q[g]=
v;h/=2;g++}d=q.length;for(r=1;1!==d;){for(t=0;t<d-1;t++)p[t]=(e.pow(4,r)*q[t+1]-q[t])/(e.pow(4,r)-1);d=p.length;q=p;p=[];r++}return q},richardson:function(d,a,b,f){function g(d,a){for(var b=0,e=d.length,n;b<e;b++)d[b]===a&&(n=b);return n}for(var h=e.abs(b-d[g(d,b)+1]),m=0,p=[],q=[],r,t;f>=h;)r=g(d,b+f),t=g(d,b),p[m]=(a[r]-2*a[t]+a[2*t-r])/(f*f),f/=2,m++;a=p.length;for(d=1;1!=a;){for(b=0;b<a-1;b++)q[b]=(e.pow(4,d)*p[b+1]-p[b])/(e.pow(4,d)-1);a=q.length;p=q;q=[];d++}return p},simpson:function(d,a,b,
e){e=(b-a)/e;var f=d(a),h=[],m=a,p=0;for(a=1;m<=b;m+=e,p++)h[p]=m;for(m=h.length;a<m-1;a++)f+=(0!==a%2?4:2)*d(h[a]);return e/3*(f+d(b))},hermite:function(d,a,b,e){for(var f=d.length,h=0,m=0,p=[],q=[],r=[],t=[],v;m<f;m++){p[m]=1;for(v=0;v<f;v++)m!=v&&(p[m]*=(e-d[v])/(d[m]-d[v]));for(v=q[m]=0;v<f;v++)m!=v&&(q[m]+=1/(d[m]-d[v]));r[m]=(1-2*(e-d[m])*q[m])*p[m]*p[m];t[m]=(e-d[m])*p[m]*p[m];h+=r[m]*a[m]+t[m]*b[m]}return h},lagrange:function(d,a,b){for(var e=0,f=0,h,m,p=d.length;f<p;f++){m=a[f];for(h=0;h<
p;h++)f!=h&&(m*=(b-d[h])/(d[f]-d[h]));e+=m}return e},cubic_spline:function(d,a,b){for(var e=d.length,g=0,h=[],m=[],p=[],q=[],r=[],t=[],v=[];g<e-1;g++)r[g]=d[g+1]-d[g];p[0]=0;for(g=1;g<e-1;g++)p[g]=3/r[g]*(a[g+1]-a[g])-3/r[g-1]*(a[g]-a[g-1]);for(g=1;g<e-1;g++)h[g]=[],m[g]=[],h[g][g-1]=r[g-1],h[g][g]=2*(r[g-1]+r[g]),h[g][g+1]=r[g],m[g][0]=p[g];q=f.multiply(f.inv(h),m);for(g=0;g<e-1;g++)t[g]=(a[g+1]-a[g])/r[g]-r[g]*(q[g+1][0]+2*q[g][0])/3,v[g]=(q[g+1][0]-q[g][0])/(3*r[g]);for(g=0;g<e&&!(d[g]>b);g++);
--g;return a[g]+(b-d[g])*t[g]+f.sq(b-d[g])*q[g]+(b-d[g])*f.sq(b-d[g])*v[g]},gauss_quadrature:function(){throw Error("gauss_quadrature not yet implemented");},PCA:function(d){var a=d.length,b=d[0].length,e=0,g,h=[],m=[];g=[];for(var p=[],q=[],r=[],r=[],m=[],e=[],t=[],e=0;e<a;e++)h[e]=f.sum(d[e])/b;for(e=0;e<b;e++)for(r[e]=[],g=0;g<a;g++)r[e][g]=d[g][e]-h[g];r=f.transpose(r);for(e=0;e<a;e++)for(m[e]=[],g=0;g<a;g++)m[e][g]=f.dot([r[e]],[r[g]])/(b-1);g=f.jacobi(m);e=g[0];m=g[1];t=f.transpose(e);for(e=
0;e<m.length;e++)for(g=e;g<m.length;g++)m[e]<m[g]&&(b=m[e],m[e]=m[g],m[g]=b,p=t[e],t[e]=t[g],t[g]=p);r=f.transpose(r);for(e=0;e<a;e++)for(q[e]=[],g=0;g<r.length;g++)q[e][g]=f.dot([t[e]],[r[g]]);return[d,m,t,q]}});(function(d){for(var a=0;a<d.length;a++)(function(d){f.fn[d]=function(a,b){var e=this;return b?(setTimeout(function(){b.call(e,f.fn[d].call(e,a))},15),this):"number"===typeof f[d](this,a)?f[d](this,a):f(f[d](this,a))}})(d[a])})("add divide multiply subtract dot pow exp log abs norm angle".split(" "))})(this.jStat,
Math);
(function(f,e){var a=[].slice,b=f.utils.isNumber;f.extend({zscore:function(){var d=a.call(arguments);return b(d[1])?(d[0]-d[1])/d[2]:(d[0]-f.mean(d[1]))/f.stdev(d[1],d[2])},ztest:function(){var d=a.call(arguments);if(4===d.length){if(b(d[1])){var n=f.zscore(d[0],d[1],d[2]);return 1===d[3]?f.normal.cdf(-e.abs(n),0,1):2*f.normal.cdf(-e.abs(n),0,1)}n=d[0];return 1===d[2]?f.normal.cdf(-e.abs(n),0,1):2*f.normal.cdf(-e.abs(n),0,1)}n=f.zscore(d[0],d[1],d[3]);return 1===d[1]?f.normal.cdf(-e.abs(n),0,1):2*
f.normal.cdf(-e.abs(n),0,1)}});f.extend(f.fn,{zscore:function(d,a){return(d-this.mean())/this.stdev(a)},ztest:function(d,a,b){d=e.abs(this.zscore(d,b));return 1===a?f.normal.cdf(-d,0,1):2*f.normal.cdf(-d,0,1)}});f.extend({tscore:function(){var d=a.call(arguments);return 4===d.length?(d[0]-d[1])/(d[2]/e.sqrt(d[3])):(d[0]-f.mean(d[1]))/(f.stdev(d[1],!0)/e.sqrt(d[1].length))},ttest:function(){var d=a.call(arguments),n;if(5===d.length)return n=e.abs(f.tscore(d[0],d[1],d[2],d[3])),1===d[4]?f.studentt.cdf(-n,
d[3]-1):2*f.studentt.cdf(-n,d[3]-1);if(b(d[1]))return n=e.abs(d[0]),1==d[2]?f.studentt.cdf(-n,d[1]-1):2*f.studentt.cdf(-n,d[1]-1);n=e.abs(f.tscore(d[0],d[1]));return 1==d[2]?f.studentt.cdf(-n,d[1].length-1):2*f.studentt.cdf(-n,d[1].length-1)}});f.extend(f.fn,{tscore:function(d){return(d-this.mean())/(this.stdev(!0)/e.sqrt(this.cols()))},ttest:function(d,a){return 1===a?1-f.studentt.cdf(e.abs(this.tscore(d)),this.cols()-1):2*f.studentt.cdf(-e.abs(this.tscore(d)),this.cols()-1)}});f.extend({anovafscore:function(){var d=
a.call(arguments),b,l,k,g,h,m;if(1===d.length){b=Array(d[0].length);for(h=0;h<d[0].length;h++)b[h]=d[0][h];d=b}if(2===d.length)return f.variance(d[0])/f.variance(d[1]);l=[];for(h=0;h<d.length;h++)l=l.concat(d[h]);k=f.mean(l);for(h=b=0;h<d.length;h++)b+=d[h].length*e.pow(f.mean(d[h])-k,2);b/=d.length-1;for(h=g=0;h<d.length;h++)for(k=f.mean(d[h]),m=0;m<d[h].length;m++)g+=e.pow(d[h][m]-k,2);g/=l.length-d.length;return b/g},anovaftest:function(){var d=a.call(arguments),e,l,k;if(b(d[0]))return 1-f.centralF.cdf(d[0],
d[1],d[2]);anovafscore=f.anovafscore(d);e=d.length-1;for(k=l=0;k<d.length;k++)l+=d[k].length;return 1-f.centralF.cdf(anovafscore,e,l-e-1)},ftest:function(d,a,b){return 1-f.centralF.cdf(d,a,b)}});f.extend(f.fn,{anovafscore:function(){return f.anovafscore(this.toArray())},anovaftes:function(){var d=0,a;for(a=0;a<this.length;a++)d+=this[a].length;return f.ftest(this.anovafscore(),this.length-1,d-this.length)}});f.extend({normalci:function(){var d=a.call(arguments),b=Array(2),l;l=4===d.length?e.abs(f.normal.inv(d[1]/
2,0,1)*d[2]/e.sqrt(d[3])):e.abs(f.normal.inv(d[1]/2,0,1)*f.stdev(d[2])/e.sqrt(d[2].length));b[0]=d[0]-l;b[1]=d[0]+l;return b},tci:function(){var d=a.call(arguments),b=Array(2),l;l=4===d.length?e.abs(f.studentt.inv(d[1]/2,d[3]-1)*d[2]/e.sqrt(d[3])):e.abs(f.studentt.inv(d[1]/2,d[2].length-1)*f.stdev(d[2],!0)/e.sqrt(d[2].length));b[0]=d[0]-l;b[1]=d[0]+l;return b},significant:function(a,b){return a<b}});f.extend(f.fn,{normalci:function(a,b){return f.normalci(a,b,this.toArray())},tci:function(a,b){return f.tci(a,
b,this.toArray())}})})(this.jStat,Math);var utils=utils||{};
(function(f){f.htmlNamespaceUri="http://www.w3.org/1999/xhtml";f.svgNamespaceUri="http://www.w3.org/2000/svg";f.xlinkUri="http://www.w3.org/1999/xlink";f.hasOwnProperty=function(e,a){var b=e.__proto__||e.constructor.prototype;return a in e&&(!(a in b)||b[a]!==e[a])};f.shuffleArray=function(e){for(var a=e.length,b,d;0!==a;)d=Math.floor(Math.random()*a),--a,b=e[a],e[a]=e[d],e[d]=b;return e};f.isObjInArray=function(e,a){var b=!1;0<=e.indexOf(a)&&(b=!0);return b};f.removeA=function(e){for(var a,b=arguments,
d=b.length,f;1<d&&e.length;)for(a=b[--d];-1!==(f=e.indexOf(a));)e.splice(f,1);return e};f.getKeys=function(e){var a=[],b;for(b in e)a.push(b);return a};f.eliminateDuplicates=function(e){for(var a=[],b=0;b<e.length;b++){var d=e[b];f.isObjInArray(a,d)||a.push(d)}return a};f.keepReplicates=function(e,a,b){for(var d={},f=0;f<e.length;f++){var l=e[f];l in d||(d[l]=0);d[l]++}a=null==a?2:a;e=[];for(l in d)null!=b&&b?d[l]<a&&e.push(l):d[l]>=a&&e.push(l);return e};f.beginsWith=function(e,a){return 0===e.indexOf(a)};
f.endsWith=function(e,a){return-1!==e.indexOf(a,e.length-a.length)};f.lengthOfLongestString=function(e){var a=[],b;for(b in e)a.push(e[b].length);return Math.max.apply(null,a)};f.isNumerical=function(e){return null==e||""===e||isNaN(e)?!1:!0};f.getListBoxSelectedValues=function(e){for(var a=[],b=0;b<e.length;b++){var d=e[b];d.selected&&a.push(d.value)}return a};f.linearInterpolation=function(e,a,b){return(b-a)*e+a};f.rangeLimit=function(e,a,b){"undefined"===typeof a&&(a=-1);"undefined"===typeof b&&
(b=1);return e<a?a:e>b?b:e};f.extractFromJq=function(e){return e.get(0)};f.convertToJq=function(e){$(e);return e};f.extractFromD3=function(e){return e.node()};f.convertToD3=function(e){return d3.select(e)};f.sort_by=function(e,a,b){var d=b?function(a){return b(a[e])}:function(a){return a[e]};a=[-1,1][+!!a];return function(b,e){return b=d(b),e=d(e),a*((b>e)-(e>b))}};f.compareAsNumeric=function(e,a){var b=parseFloat(e),d=parseFloat(a);if(utils.isNumerical(b)&&utils.isNumerical(d)){if(b<d)return-1;if(b>
d)return 1}else if(b==b||d==d){if(b!=b)return-1;if(d!=d)return 1}return 0};f.compareAsString=function(e,a){var b=new String(e),d=new String(a);return"null"==b&&"null"!=d?1:"null"!=b&&"null"==d?-1:b.localeCompare(d)};f.compareAsDate=function(e,a){var b=e,d=a;null==b?b="1000":""==b&&(b="1001");null==d?d="1000":""==d&&(d="1001");return new Date(b)-new Date(d)};f.rgbComponentToHex=function(e){e=e.toString(16);return 1==e.length?"0"+e:e};f.rgbToHex=function(e,a,b){return"#"+this.rgbComponentToHex(e)+this.rgbComponentToHex(a)+
this.rgbComponentToHex(b)};f.centeredRgbaColorMapper=function(e,a,b,d){var f=null,l=null==a?0:a,k=null==b?-1.96:b,g=null==d?1.96:d;return f=function(a){var d=1,b=169,f=169,n=169;a=parseFloat(a);null!=a&&a==a&&(a>l?(b=255,n=f=0,a>g?d=1:(d=(a-l)/(g-l),d=Math.abs(d),e&&(d=Math.log(d)))):a<l?(f=b=0,n=255,a<k?d=1:(d=(a-l)/(k-l),d=Math.abs(d),e&&(d=Math.log(d)))):(n=f=b=255,d=1));return"rgba("+b+","+f+","+n+","+d+")"}};f.setupQuantileColorMapper=function(e,a){var b=a;null==b&&(b="rgb(255,255,217) rgb(237,248,177) rgb(199,233,180) rgb(127,205,187) rgb(65,182,196) rgb(29,145,192) rgb(34,94,168) rgb(37,52,148) rgb(8,29,88)".split(" "));
var d=b.length;return d3.scale.quantile().domain([0,d-1,d3.max(e,function(a){return parseFloat(a)})]).range(b)};f.getXmlDom_url=function(e){xmlhttp=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");xmlhttp.open("GET",e,!1);xmlhttp.send();return xmlDoc=xmlhttp.responseXML};f.getXmlDom_string=function(e){window.DOMParser?(parser=new DOMParser,xmlDoc=parser.parseFromString(e,"text/xml")):(xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),xmlDoc.async=!1,xmlDoc.loadXML(e));return xmlDoc};
f.getDateTime=function(){var e=new Date,a=e.getFullYear(),b=e.getMonth()+1,d=e.getDate(),f=e.getHours(),l=e.getMinutes(),e=e.getSeconds();1==b.toString().length&&(b="0"+b);1==d.toString().length&&(d="0"+d);1==f.toString().length&&(f="0"+f);1==l.toString().length&&(l="0"+l);1==e.toString().length&&(e="0"+e);return a+"/"+b+"/"+d+" "+f+":"+l+":"+e};f.todaysDate=function(){var e=new Date,a=e.getDate();e.getDay();var b=e.getMonth()+1,e=e.getYear();return[,"January","February","March","April","May","June",
"July","August","September","October","November","December"][b]+" "+a+", "+(1E3>e?e+1900:e)};f.pushElemToBack=function(e){var a=e.parentNode;a.insertBefore(e,a.firstChild);return e};f.pullElemToFront=function(e){e.parentNode.appendChild(e);return e};f.removeElemById=function(e){e=document.getElementById(e);e.parentNode.removeChild(e)};f.removeChildElems=function(e){for(;e.firstChild;)e.removeChild(e.firstChild);return e};f.createDivElement=function(e,a){var b=document.createElement("div");null!=e&&
(b.id=e);null!=a&&(b.className=a);return b};f.setElemAttributes=function(e,a,b){b="undefined"===typeof b?null:b;if(null!=a)for(var d in a)e.setAttributeNS(b,d,a[d]);return e};f.swapContainingDivs=function(e,a){var b=a.parentNode;document.getElementById(e.parentNode.id).appendChild(a);document.getElementById(b.id).appendChild(e)};f.simpleAsyncGet=function(e,a){var b=new XMLHttpRequest,b=window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");b.onreadystatechange=function(){this.readyState===
(this.DONE||4)&&(200==this.status?a(this.responseText):400==this.status?console.log("There was an error 400"):console.log("status was not 200",this.status))};b.open("GET",e,!0);b.setRequestHeader("X-Requested-With","XMLHttpRequest");b.send(null)};f.getResponse=function(e){var a=null,b=null,b=new XMLHttpRequest;b.open("GET",e,!1);b.onload=function(){a=b.status;200!=a&&console.log("xhr status: "+a+" for "+e)};b.send(null);var d=null;200==a&&(d=b.responseText);return d};f.loadNewSettings=function(e){e=
window.location.pathname+"?query="+JSON.stringify(e);window.open(e,"_self")};f.getQueryObj=function(){var e={};location.search.slice(1).split("&").forEach(function(a){a=a.split("=");e[a[0]]=decodeURIComponent(a[1])||""});return e};f.getQueryStringParameterByName=function(e){e=e.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");e=(new RegExp("[\\?&]"+e+"=([^&#]*)")).exec(location.search);return null==e?"":decodeURIComponent(e[1].replace(/\+/g," "))};f.parseJson=function(e){return JSON.parse(e)};f.serializeJson=
function(e,a){return a?JSON.stringify(e,null,"\t"):JSON.stringify(e)};f.prettyJson=function(e){return this.serializeJson(e,!0)};f.bottomRoundedRectSvgPath=function(e,a,b,d,f){e=""+("M"+e+","+a)+("h"+b);e+="v"+(d-f);e+="a"+f+","+f+" 0 0 1 "+-1*f+","+f;e+="h"+-1*(b-2*f);e+="a"+f+","+f+" 0 0 1 "+-1*f+","+-1*f;e+="v"+-1*(d-f);return e+="z"};f.allRoundedRectSvgPath=function(e,a,b,d,f){e=""+("M"+e+","+(a+f))+("a"+f+","+f+" 0 0 1 "+f+","+-1*f);e+="h"+(b-2*f);e+="a"+f+","+f+" 0 0 1 "+f+","+f;e+="v"+(d-2*
f);e+="a"+f+","+f+" 0 0 1 "+-1*f+","+f;e+="h"+-1*(b-2*f);e+="a"+f+","+f+" 0 0 1 "+-1*f+","+-1*f;e+="v"+-1*(d-2*f);return e+="z"};f.allAngledRectSvgPath=function(e,a,b,d){var f=b>d?b/8:d/8;e=""+("M"+(e+f)+","+a)+("h"+(b-2*f));e+="l"+f+","+f;e+="v"+(d-2*f);e+="l"+-1*f+","+f;e+="h"+-1*(b-2*f);e+="l"+-1*f+","+-1*f;e+="v"+-1*(d-2*f);return e+="z"};f.createSvgRingElement=function(e,a,b,d){function f(a,d,b,e){e=(e-90)*Math.PI/180;return{x:a+b*Math.cos(e),y:d+b*Math.sin(e)}}e=function(a,d,b,e,l){var q=f(a,
d,b,l);a=f(a,d,b,e);return["M",q.x,q.y,"A",b,b,0,180>=l-e?"0":"1",0,a.x,a.y].join(" ")}(e,a,b,0,359.9);a=document.createElementNS(this.svgNamespaceUri,"path");a.setAttributeNS(null,"d",e);if(null!=d)for(var l in d)a.setAttributeNS(null,l,d[l]);return a};f.createSvgCircleElement=function(e,a,b,d){var f=document.createElementNS(this.svgNamespaceUri,"circle");f.setAttributeNS(null,"cx",e);f.setAttributeNS(null,"cy",a);f.setAttributeNS(null,"r",b);if(null!=d)for(var l in d)f.setAttributeNS(null,l,d[l]);
return f};f.createSvgRectElement=function(e,a,b,d,f,l,k){var g=document.createElementNS(this.svgNamespaceUri,"rect");g.setAttributeNS(null,"x",e);g.setAttributeNS(null,"y",a);g.setAttributeNS(null,"rx",b);g.setAttributeNS(null,"ry",d);g.setAttributeNS(null,"width",f);g.setAttributeNS(null,"height",l);if(null!=k)for(var h in k)g.setAttributeNS(null,h,k[h]);return g};f.createSVGPolygonElement=function(e){var a=document.createElementNS(this.svgNamespaceUri,"polygon");if(null!=e)for(var b in e)a.setAttributeNS(null,
b,e[b]);return a};f.createSvgImageElement=function(e,a,b,d,f,l){var k=document.createElementNS(this.svgNamespaceUri,"image");k.setAttributeNS(this.xlinkUri,"href",e);k.setAttributeNS(null,"x",a);k.setAttributeNS(null,"y",b);k.setAttributeNS(null,"width",d);k.setAttributeNS(null,"height",f);if(null!=l)for(var g in l)k.setAttributeNS(null,g,l[g]);return k};f.setCookie=function(e,a,b){if(b){var d=new Date;d.setTime(d.getTime()+864E5*b);b="; expires="+d.toGMTString()}else b="";document.cookie=e+"="+a+
b+"; path=/"};f.getCookie=function(e){e+="=";for(var a=document.cookie.split(";"),b=0;b<a.length;b++){for(var d=a[b];" "==d.charAt(0);)d=d.substring(1,d.length);if(0==d.indexOf(e))return d.substring(e.length,d.length)}return null};f.deleteCookie=function(e){this.setCookie(e,"",-1)};f.getNormalizedVector=function(e){var a=[],b=jStat.min(e),d=jStat.max(e);if(0>b||0==d){console.log("min:"+b+"\tmax:"+d);if(0>b)return null;if(0==d)return e}for(b=0;b<e.length;b++)a.push(e[b]/d);return a};f.computeMarginalEntropy=
function(e,a){for(var b=0,d=[],f=a(e),l=0;l<f.length;l++)d.push({bin:l,count:f[l].length});for(l=0;l<d.length;l++)f=d[l],f.probability=f.count/e.length,f.prod=0==f.probability?0:f.probability*Math.log2(f.probability),b+=f.prod;return-1*b};f.computeJointEntropy=function(e,a,b){if(e.length!=a.length)return null;var d=function(a,d){for(var b=null,e=0;e<a.length;e++){var f=a[e];d>=f.x&&d<f.x+f.dx&&(b=e)}null==b&&(f=a[a.length-1],d-f.x-f.dx<f.dx&&(b=a.length-1));return b},n=b(e),l=b(a);b={};for(var k=
0;k<n.length;k++)for(var g=0;g<l.length;g++){var h=k+"_"+g;b[h]=0}for(k=0;k<e.length;k++)h=d(n,e[k]),g=d(l,a[k]),h=h+"_"+g,b[h]++;a=0;d=f.getKeys(b);for(k=0;k<d.length;k++)h=d[k],n=b[h]/e.length,n=0==n?0:n*Math.log2(n),a+=n;return-1*a};f.mutualInformation=function(e,a,b){b="undefined"===typeof b?e.length:b;var d=d3.layout.histogram().bins(b).frequency(!1);b=f.computeMarginalEntropy(e,d);var n=f.computeMarginalEntropy(a,d);e=f.computeJointEntropy(e,a,d);return b+n-e}})(utils);var eventData=eventData||{};
(function(f){f.getEventElems=function(e,a){var b=[];e.find("event").each(function(d,e){var f=e.getAttribute("type");void 0===a||null===a?b.push(e):f===a&&b.push(e)});return b};f.getEventParentChildren=function(e,a){var b={parent:null,children:[]},d=f.getEventElems(e,a);$(d).each(function(a,d){if("event"!==d.tagName)return"continue";b.parent=d.parentNode.getAttribute("type");$(d.children).each(function(a,d){"event"===d.tagName&&b.children.push(d.getAttribute("type"))})});return b};f.tracebackToRoot=
function(e,a){for(var b=[],d=f.getEventElems(e,a),n=0;n<d.length;n++){var l=d[n],k=[];b.push(k);l=l.getAttribute("type");for(l=f.getEventParentChildren(e,l).parent;void 0!==l&&null!==l;)k.push(l),l=f.getEventParentChildren(e,l).parent}return b};f.OD_eventAlbum=function(){this.album={};this.datatypeSuffixMapping={};this.pivot={};this.getSuffixedEventId=function(e,a){return e+(a in this.datatypeSuffixMapping?this.datatypeSuffixMapping[a]:"")};this.addEvent=function(e,a){var b=new f.OD_event(e);this.album[e.id]=
b;"datatype"in e&&"geneSuffix"in e&&(this.datatypeSuffixMapping[e.datatype]=e.geneSuffix);b.data.setData(a,"numeric"==e.allowedValues||"expression"==e.allowedValues);return b};this.deleteEvent=function(e){delete this.album[e]};this.getAllEventIds=function(){var e=[],a=this.getEventIdsByType(),b;for(b in a)e=e.concat(a[b]);return e};this.getEventIdsByType=function(){for(var e={},a=utils.getKeys(this.album),b=0;b<a.length;b++){var d=a[b],f=this.getEvent(d).metadata.datatype;utils.hasOwnProperty(e,f)||
(e[f]=[]);e[f].push(d)}return e};this.getEventData=function(e){for(var a={},b=utils.getKeys(this.album),d=0;d<b.length;d++){var f=b[d],l=this.getEvent(f).data.getData(e);a[f]=l}return a};this.getAllDataAsList=function(){for(var e=[],a=this.getEventData(),b=utils.getKeys(a),d=0;d<b.length;d++){for(var f=b[d],l=a[f].slice(),k=0;k<l.length;k++)l[k].eventId=f;e=e.concat(l)}return e};this.getAllSampleIds=function(){for(var e=[],a=utils.getKeys(this.album),b=0;b<a.length;b++)var d=this.getEvent(a[b]).data.getAllSampleIds(),
e=e.concat(d);return utils.eliminateDuplicates(e)};this.selectSamples=function(e){var a=this.getAllSampleIds();if(0==e.length)return a;for(var b in e)var d=e[b].value,a=this.getEvent(e[b].eventId).data.selectIds(d,a);return a};this.getEvent=function(e){var a=this.album[e];"undefined"===typeof a&&console.log("getEvent got undefined eventObj for: "+e);return a};this.getAllChildren=function(e,a){for(var b="undefined"===typeof a?[]:a,d=[],f=0;f<e.length;f++)var l=this.getEvent(e[f]).metadata,d=d.concat(getKeys(l.children));
if(0==d.length)return b;b=b.concat(d);return this.getAllChildren(d,b)};this.setPivotScores_dict=function(e,a){this.pivot=null==a?{}:{event:e,scores:a};return this};this.setPivotScores_array=function(e,a){null==a?this.pivot={}:(a=a.sort(utils.sort_by("score")),this.pivot={event:e,scores:a});return this};this.getPivotSortedEvents=function(e){if("undefined"===typeof this.pivot.scores||null==this.pivot.scores)return console.log("getPivotSortedEvents found no pivot scores"),[];for(var a=[],b={},d=0,f=
this.pivot.scores.length;d<f;d++){var l=this.pivot.scores[d],k=l.eventId1,g=l.eventId2,l=l.score;if(k===e)k=g;else if(g!==e)continue;utils.hasOwnProperty(b,k)||(a.push({key:k,val:parseFloat(l)}),b[k]=1)}return a=a.sort(utils.sort_by("val"))};this.getGroupedPivotSorts=function(e,a){console.log("getGroupedPivotSorts");for(var b=["expression data","expression signature"],d={},b=this.getPivotSortedEvents(e),f=[],l=0;l<b.length;l++)f.push(b[l].key);var l=this.getEventIdsByType(),b=utils.getKeys(l),b=utils.removeA(b,
"clinical data"),k;for(k in l){var g=[],h=l[k];if(0==f.length)console.log("pivotSortedEvents.length == 0 for "+k),d[k]=h;else{for(var m=0;m<f.length;m++){var p=this.getSuffixedEventId(f[m],k);utils.isObjInArray(h,p)&&g.push(p)}utils.isObjInArray(b,k)||(g=g.concat(h),g=utils.eliminateDuplicates(g));d[k]=g}}return d};this.getAllPivotScores=function(e,a){var b={},d=this.getEventIdsByType();if(!utils.hasOwnProperty(d,e))return b;for(var d=d[e],f=0;f<d.length;f++){var l=d[f],k=this.pivotSort(l,a);b[l]=
k}return b};this.pivotSort_2=function(e,a){for(var b=this.pivotSort(e,jStat.corrcoeff),d={},f=0;f<b.length;f++){var l=b[f],k=l.event;d[k]=0>l.score?-1:1}for(var b=this.pivotSort(e,a),g=[],h=[],f=0;f<b.length;f++)l=b[f],k=l.event,0>d[k]?h.push(l):g.push(l);g.sort(utils.sort_by("score"));h.sort(utils.sort_by("score"),!0);return g.concat(h)};this.pivotSort=function(e,a){console.log("eventAlbum.pivotSort:",e);"undefined"===typeof a&&(console.log("using default scoringAlgorithm, jStat.corrcoeff"),a=jStat.corrcoeff);
var b=this.getEvent(e);if(null==b)return console.log("eventObj not found for",e),null;for(var d=b.data.getAllSampleIds(),f=b.data.getNullSamples(),d=utils.keepReplicates(d.concat(f),2,!0),f=this.getEventIdsByType()[b.metadata.datatype],l=[],k=0;k<f.length;k++){var g=f[k],h=this.getEvent(g),m=h.data.getAllSampleIds(),p=h.data.getNullSamples(),m=utils.keepReplicates(m.concat(p),2,!0),m=utils.keepReplicates(m.concat(d)),p=b.data.getData(m),h=h.data.getData(m);if(0<h.length){var q=[],r=[],t=null;null==
t&&(t=utils.hasOwnProperty(p[0],"val_orig")?"val_orig":"val");for(var v=null,z=0;z<m.length;z++)null==v&&(v=utils.hasOwnProperty(h[z],"val_orig")?"val_orig":"val"),q.push(p[z][t]),r.push(h[z][v]);m=a(q,r);l.push({event:g,score:m})}else console.log("eventData2 is empty")}l.sort(utils.sort_by("score"));return l};this.multisortEvents=function(e,a){console.log("multisortEvents");console.log("rowSortSteps",e);console.log("colSortSteps",a);var b=this.getEventIdsByType();console.log("groupedEvents",b);var d=
[],f;for(f in b)if("datatype label"!==f){var l=b[f];l.unshift(f+"(+)");l.push(f+"(-)");d=d.concat(l)}l=[];if(null!=a){for(var k=a.getSteps(),g=0;g<k.length;g++){f=k[g];var h=f.name;l.push(h)}l.reverse()}var m=l.slice(0),m=m.concat(d),m=utils.eliminateDuplicates(m);if(null!=e)for(k=e.getSteps().reverse(),g=0;g<k.length;g++){f=k[g];h=f.name;d=f.reverse;h=this.getEvent(h);f=h.metadata.datatype;var p=h.metadata.scoredDatatype;if(null==p)console.log("no scored datatype to sort");else if(h=h.metadata.sortSignatureVector(),
d&&h.reverse(),utils.hasOwnProperty(b,p)){g=b[p].slice(0);k=[];m=[];for(d=0;d<h.length;d++){var q=this.getSuffixedEventId(h[d],p),r=g.indexOf(q);0<=r&&m.push(q);0<=r&&!utils.isObjInArray(l,q)&&(k.push(q),delete g[r]);utils.isObjInArray(l,q)&&delete g[r]}console.log("scoredEventSigWeightOverlap",m.length,m);for(var t in g)k.push(g[t]);d=l.slice(0);for(f in b)if(f===p)d=d.concat(k);else{var l=b[f],v;for(v in l)h=l[v],utils.isObjInArray(d,h)||d.push(h)}m=d;console.log("rowNames.length",m.length,m);break}else console.log(p+
" group has no events")}return m};this.multisortSamples=function(e){var a=this.getAllSampleIds();if(null==e)return console.log("multisortSamples got null steps"),a;console.log("multisortSamples using steps:",e.getSteps());var b=e.getSteps().slice();b.reverse();var d=this;a.sort(function(a,e){for(var f=0,g=0;g<b.length;g++){var h=b[g].name,m=b[g].reverse,p=d.getEvent(h);if(void 0==p||null==p){for(var q in d.datatypeSuffixMapping){var r=h+d.datatypeSuffixMapping[q],p=d.getEvent(r);if(void 0!=p&&null!=
p){h=r;break}}if(void 0==p||null==p){console.log("no event found for sorting: "+h);continue}}f=p.metadata.allowedValues;h=p.data.getData([a,e]);p=h[0].val;r=h[1].val;h=null;h="numeric"==f?utils.compareAsNumeric:"categoric"==f?utils.compareAsString:"expression"==f?utils.compareAsNumeric:"date"==f?utils.compareAsDate:utils.compareAsString;f=h(p,r);h==utils.compareAsNumeric&&(f*=-1);m&&(f*=-1);if(0!=f)break}return f});return a};this.zScoreExpressionRescaling=function(){console.log("zScoreExpressionRescaling");
var e=this.getEventIdsByType();if(!utils.hasOwnProperty(e,"expression data"))return console.log("no expression"),null;for(var e=e["expression data"],a={},b={stats:a},d=[],f=0;f<e.length;f++){var l=e[f],k=this.getEvent(l).data.getStats();a[l]={};a[l]=k;for(var k=this.getEvent(l).data.getData(),g=0;g<k.length;g++){var h=k[g];utils.hasOwnProperty(h,"val_orig")&&(h.val=h.val_orig);var m=h.val;h.val_orig=m;utils.isNumerical(m)&&(h.val=(m-a[l].mean)/a[l].sd,d.push(h.val))}}b.maxVal=jStat.max(d);b.minVal=
jStat.min(d);return b};this.betweenMeansExpressionRescaling=function(e,a,b){console.log("betweenMeansExpressionRescaling",e,a,b);a=this.getEvent(e).data.selectIds(a);var d=null;null==b?(d=this.getEvent(e).data.selectIds(b),d=d.concat(a),d=utils.eliminateDuplicates(d)):d=this.getEvent(e).data.selectIds(b);e=this.getEventIdsByType();if(!utils.hasOwnProperty(e,"expression data"))return console.log("no expression"),null;e=e["expression data"];b={};for(var f={meanVals:b},l=[],k=0;k<e.length;k++){var g=
e[k];b[g]={};b[g].group1=this.getEvent(g).data.getStats(a).mean;b[g].group2=this.getEvent(g).data.getStats(d).mean;for(var h=(b[g].group2-b[g].group1)/2,g=this.getEvent(g).data.getData(),m=0;m<g.length;m++){var p=g[m];utils.hasOwnProperty(p,"val_orig")&&(p.val=p.val_orig);var q=p.val;p.val_orig=q;utils.isNumerical(q)&&(p.val=q-h,l.push(p.val))}}f.maxVal=jStat.max(l);f.minVal=jStat.min(l);return f};this.yuliaExpressionRescaling=function(e,a){console.log("yuliaExpressionRescaling",e,a);var b=this.getEvent(e).data.selectIds(a),
d=this.getEventIdsByType();if(!utils.hasOwnProperty(d,"expression data"))return console.log("no expression"),null;for(var d=d["expression data"],f={},l={meanVals:f},k=[],g=0;g<d.length;g++){var h=d[g];f[h]=this.getEvent(h).data.getStats(b).mean;for(var m=this.getEvent(h).data.getData(),p=0;p<m.length;p++){var q=m[p];utils.hasOwnProperty(q,"val_orig")&&(q.val=q.val_orig);var r=q.val;q.val_orig=r;utils.isNumerical(r)&&(q.val=r-f[h],k.push(q.val))}}l.maxVal=jStat.max(k);l.minVal=jStat.min(k);return l};
this.eventwiseMedianRescaling=function(){console.log("eventwiseMedianRescaling");var e=this.getEventIdsByType();if(!utils.hasOwnProperty(e,"expression data"))return console.log("no expression"),null;for(var e=e["expression data"],a={},b={stats:a},d=[],f=0;f<e.length;f++){var l=e[f];this.getEvent(l);var k=this.getEvent(l).data.getStats();a[l]={};a[l]=k;for(var k=this.getEvent(l).data.getData(),g=0;g<k.length;g++){var h=k[g];utils.hasOwnProperty(h,"val_orig")&&(h.val=h.val_orig);var m=h.val;h.val_orig=
m;utils.isNumerical(m)&&(h.val=m-a[l].median,d.push(h.val))}}b.maxVal=jStat.max(d);b.minVal=jStat.min(d);return b};this.samplewiseMedianRescaling=function(){console.log("samplewiseMedianRescaling");var e=this.getEventIdsByType();if(!utils.hasOwnProperty(e,"expression data"))return console.log("no expression"),null;for(var e=e["expression data"],a={},b={stats:a},d=[],f=this.getAllSampleIds(),l=0;l<f.length;l++){var k=f[l];a[k]={};for(var g=this.getEventData([k]),h=[],m=0;m<e.length;m++){var p=e[m];
if(utils.hasOwnProperty(g,p)){if(p=g[p][0],p.id===k){utils.hasOwnProperty(p,"val_orig")&&(p.val=p.val_orig);var q=p.val;p.val_orig=q;utils.isNumerical(q)&&h.push(q)}}else console.log(p+" was not found for "+k)}h=jStat.median(h);a[k]["samplewise median"]=h;if(isNaN(h))console.log("sample median for "+k+" is NaN.");else for(m=0;m<e.length;m++)p=e[m],utils.hasOwnProperty(g,p)?(p=g[p][0],p.id===k&&(utils.hasOwnProperty(p,"val_orig")&&(p.val=p.val_orig),q=p.val,p.val_orig=q,utils.isNumerical(q)&&(p.val=
q-a[k]["samplewise median"],d.push(q)))):console.log(p+" was not found for "+k)}b.maxVal=jStat.max(d);b.minVal=jStat.min(d);return b};this.bivariateNormalization=function(){};this.removeEmptyEvents=function(e){e=e||.99;for(var a=this.getEventIdsByType(),b=[],d=utils.getKeys(a),f=0,l=d.length;f<l;f++){var k=d[f];if("datatype label"!==k)for(var g=0;g<a[k].length;g++){var h=a[k][g];this.getEvent(h).data.getPercentNullData()>=e&&b.push(h)}}f=0;for(l=b.length;f<l;f++)h=b[f],console.log("empty event:",
h),this.deleteEvent(h);return null};this.fillInMissingSamples=function(e){for(var a=this.getAllSampleIds(),b=this.getEventIdsByType(),d=0,f=utils.getKeys(b).length;d<f;d++)for(var l=utils.getKeys(b)[d],k=0;k<b[l].length;k++){var g=b[l][k],h=this.getEvent(g).data.getAllSampleIds();if(0!=a.length-h.length){for(var h=utils.keepReplicates(a.concat(h),2,!0),m={},p=0;p<h.length;p++)m[h[p]]=e;this.getEvent(g).data.setData(m)}}return this};this.fillInDatatypeLabelEvents=function(e){for(var a=this.getEventIdsByType(),
a=utils.getKeys(a),b=0,d=a.length;b<d;b++){var f=a[b];"datatype label"!==f&&(this.addEvent({id:f+"(+)",name:f+"(+)",displayName:f+"(+)",description:null,datatype:"datatype label",allowedValues:null},{}),this.addEvent({id:f+"(-)",name:f+"(-)",displayName:f+"(-)",description:null,datatype:"datatype label",allowedValues:null},{}))}this.fillInMissingSamples(e)}};f.OD_event=function(e){this.metadata=new f.OD_eventMetadata(e);this.data=new f.OD_eventDataCollection};f.OD_eventMetadata=function(e){this.id=
e.id;this.name=e.name;this.displayName=e.displayName;this.description=e.description;this.datatype=e.datatype;this.allowedValues=e.allowedValues;this.minAllowedVal=e.minAllowedVal;this.maxAllowedVal=e.maxAllowedVal;this.weightedGeneVector=[];this.setScoreRange=function(a,b){this.minAllowedVal=a;this.maxAllowedVal=b};this.setWeightVector=function(a,b){this.weightedGeneVector=a;this.scoredDatatype=b;return this};this.sortSignatureVector=function(a){var b=this.weightedGeneVector.slice(0);b.sort(function(a,
d){return utils.compareAsNumeric(a.weight,d.weight)});for(var d=[],e=0;e<b.length;e++)d.push(b[e].gene);a||d.reverse();return d}};f.OD_eventDataCollection=function(){function e(a,b){this.id=a;this.val=b}this.dataCollection=[];this.getPercentNullData=function(){var a=this.getValueCounts(),b=0;null in a&&(b=this.getAllSampleIds().length,b=a[null]/b);return b};this.getValueCounts=function(a){var b={};a=this.getData(a);for(var d=0;d<a.length;d++){var e=a[d].val;utils.hasOwnProperty(b,e)||(b[e]=0);b[e]+=
1}return b};this.getValues=function(a){var b=this.getValueCounts(),b=utils.getKeys(b);null!=a&&1==a&&(b=utils.eliminateDuplicates(b));return b};this.setData=function(a,b){for(var d in a){var f=a[d];"NaN"!=f&&"null"!=f&&""!=f&&"N/A"!=f&&(null!=b&&1==b&&(f=parseFloat(f)),this.dataCollection.push(new e(d,f)))}return this};this.getData=function(a){var b=this.getAllSampleIds(!0);null==a&&(a=utils.getKeys(b));for(var d=[],f=0;f<a.length;f++){var l=a[f];l in b?d.push(this.dataCollection[b[l]]):d.push(new e(l,
null))}return d};this.getAllSampleIds=function(a){for(var b={},d=0;d<this.dataCollection.length;d++)b[this.dataCollection[d].id]=d;return a?b:utils.getKeys(b)};this.getNullSamples=function(a){var b=[];a=this.getData(a);for(var d=0;d<a.length;d++){var e=a[d];null==e.val&&b.push(e.id)}return b};this.sortSamples=function(a,b){var d=this.getData(a),e=compareSamplesAsStrings;b=null==b?"categoric":b.toLowerCase();"numeric"==b||"expression"==b?e=compareSamplesAsNumeric:"date"==b&&(e=compareSamplesAsDate);
d.sort(e);for(var e=[],f=0;f<d.length;f++)e.push(d[f].id);return e};this.selectIds=function(a,b){for(var d=[],e=null==b?this.getData():this.getData(b),f=0;f<e.length;f++){var k=e[f];k.val==a&&d.push(k.id)}return d};this.getStats=function(a,b){"undefined"===typeof b&&(b=3);var d={min:0,max:0,mean:0,median:0,sd:0,meddev:0,meandev:0,percentNullData:0};d.percentNullData=this.getPercentNullData();d.percentNullData=d.percentNullData.toPrecision(b);if(1==d.percentNullData)return d;var e=this.getAllSampleIds(!0);
null==a&&(a=utils.getKeys(e));for(var f=[],k=0;k<a.length;k++){var g=a[k];if(g in e){var g=this.dataCollection[e[g]],h=null,h=utils.hasOwnProperty(g,"val_orig")?g.val_orig:g.val;utils.isNumerical(h)&&f.push(h)}}d.mean=jStat.mean(f).toPrecision(b);d.sd=jStat.stdev(f).toPrecision(b);d.median=jStat.median(f).toPrecision(b);d.meddev=jStat.meddev(f).toPrecision(b);d.meandev=jStat.meandev(f).toPrecision(b);d.min=jStat.min(f).toPrecision(b);d.max=jStat.max(f).toPrecision(b);return d}};f.sortingSteps=function(e){this.steps=
[];null!=e&&(this.steps=e);this.getSteps=function(){return this.steps};this.getIndex=function(a){for(var b=0;b<this.steps.length;b++)if(this.steps[b].name==a)return b;return-1};this.addStep=function(a,b){var d=this.getIndex(a);0<=d?(d=this.steps.splice(d,1)[0],b||(d.reverse=!d.reverse),this.steps.push(d)):this.steps.push({name:a,reverse:!1})};this.removeStep=function(a){a=this.getIndex(a);0<=a&&this.steps.splice(a,1)};this.clearSteps=function(){this.steps.splice(0,this.steps.length)}};f.sampleSelectionCriteria=
function(){this.criteria=[];this.getCriteria=function(){return this.criteria};this.addCriteria=function(e,a){var b={eventId:e,value:a},d;for(d in this.criteria)if(JSON.stringify(this.criteria[d])==JSON.stringify(b))return;this.criteria.push(b)};this.removeCriteria=function(e,a){for(var b=0;b<this.criteria.length;b++)if(this.criteria[b].eventId==e&&this.criteria[b].value==a){this.criteria.splice(b,1);break}};this.clearCriteria=function(){this.criteria.splice(0,this.criteria.length)}}})(eventData);var graphData={};
(function(f){f.nodeData=function(e){this.name=e.name;this.group="group"in e?e.group:"unspecified entity";this.checkEquality=function(a){return this.name==a.name&&this.group==a.group?!0:!1}};f.linkData=function(e){this.source=parseInt(e.sourceIdx);this.target=parseInt(e.targetIdx);this.value="value"in e?parseFloat(e.value):3;"relation"in e&&(this.relation=e.relation)};f.graphData=function(){this.nodes=[];this.links=[];this.getAllNodeNames=function(){for(var e=[],a=0,b=this.nodes.length;a<b;a++)e.push(this.nodes[a].name);
return e};this.addNode=function(e){if(e.constructor.toString!==f.nodeData.constructor.toString)return console.log("not nodeData: "+JSON.stringify(e)),null;for(var a=!1,b=0,d=this.nodes.length;b<d;b++)if(this.nodes[b].checkEquality(e)){console.log("nodeData exists");a=!0;break}if(a)return null;this.nodes.push(e);return e};this.addLink=function(e){if(e.constructor.toString!==f.linkData.constructor.toString)return console.log("not adding link: "+JSON.stringify(e)),null;this.links.push(e)};this.getNodeIdsByName=
function(e){var a=[];e=e.toUpperCase(e);for(var b=0,d=this.nodes.length;b<d;b++)this.nodes[b].name.toUpperCase()===e&&a.push(b);return a};this.deleteNodeByName=function(e){if(1>this.nodes.length)console.log("no nodes to delete");else{for(var a=-1,b=0,d=this.nodes.length;b<d;b++)if(this.nodes[b].name==e){a=b;break}if(-1==a)console.log("No node was found for "+e);else{e=[];b=0;for(d=this.links.length;b<d;b++){var f=this.links[b],l=f.source,k=f.target;l==a||k==a?e.push(f):l.index!=a&&k.index!=a||e.push(f)}b=
0;for(d=e.length;b<d;b++)f=e[b],utils.removeA(this.links,f);utils.removeA(this.nodes,this.nodes[a])}}};this.deleteLinkByIndex=function(e){this.links.splice(e,1)};this.readTab=function(e){this.nodes=[];this.links=[];e=e.split("\n");for(var a=[],b=0,d=e.length;b<d;b++){var f=e[b].split("\t");if(2<=f.length){var l=f[0],k=f[1];a.push(l);a.push(k)}}a=d3.set(a).values();b=0;for(d=a.length;b<d;b++)this.addNode(new nodeData({name:a[b]}));b=0;for(d=e.length;b<d;b++)f=e[b].split("\t"),2<=f.length&&(l=f[0],
k=f[1],a="",a=3<=f.length?f[2]:"unspecified",f=this.getNodeIdsByName(l),k=this.getNodeIdsByName(k),this.addLink(new linkData({sourceIdx:f[0],targetIdx:k[0],relation:a})))};this.readSif=function(e){this.nodes=[];this.links=[];e=e.split("\n");for(var a=[],b=0,d=e.length;b<d;b++){var n=e[b].split("\t");if(3<=n.length){var l=n[0],n=n[2];a.push(l);a.push(n)}}a=d3.set(a).values();b=0;for(d=a.length;b<d;b++)this.addNode(new f.nodeData({name:a[b]}));b=0;for(d=e.length;b<d;b++)n=e[b].split("\t"),3<=n.length&&
(l=n[0],a=n[1],n=n[2],l=this.getNodeIdsByName(l),n=this.getNodeIdsByName(n),this.addLink(new f.linkData({sourceIdx:l[0],targetIdx:n[0],relation:a})))};this.readMedbookGraphData=function(e){this.nodes=[];this.links=[];for(var a=e.network.elements,b=0,d=a.length;b<d;b++){var n=a[b];this.addNode(new f.nodeData({name:n.name,group:n.type}))}e=e.network.interactions;console.log("medbookInteractions.length",e.length);b=0;for(a=e.length;b<a;b++){for(var l=e[b],d=l.source,n=l.target,l=l.type,k=-1,g=-1,h=0,
m=this.nodes.length;h<m;h++){var p=this.nodes[h].name;p==d&&(k=h);p==n&&(g=h);if(-1!=g&&-1!=k)break}-1!=g&&-1!=k&&this.addLink(new f.linkData({sourceIdx:parseInt(k),targetIdx:parseInt(g),relation:l}))}return null};this.readPid=function(e){this.nodes=[];this.links=[];e=e.split("\n");for(var a=0,b=e.length;a<b;a++){var d=e[a].split("\t");2==d.length&&this.addNode(new nodeData({name:d[1],group:d[0]}))}a=0;for(b=e.length;a<b;a++)if(d=e[a].split("\t"),3<=d.length){for(var f=d[0],l=d[1],d=d[2],k=-1,g=-1,
h=0,b=this.nodes.length;h<b;h++){var m=this.nodes[h].name;m==f&&(k=h);m==l&&(g=h);if(-1!=g&&-1!=k)break}-1!=g&&-1!=k&&this.addLink(new linkData({sourceIdx:parseInt(k),targetIdx:parseInt(g),relation:d}))}};this.toPid=function(){for(var e="",a=0,b=this.nodes.length;a<b;a++)var d=this.nodes[a],e=e+(d.group+"\t"+d.name+"\n");a=0;for(b=this.links.length;a<b;a++){var d=this.links[a],f=d.value;"relation"in d&&(f=d.relation);e+=d.source.name+"\t"+d.target.name+"\t"+f+"\n"}return e};this.toCytoscapeElements=
function(){for(var e={nodes:[],edges:[]},a=0,b=this.nodes.length;a<b;a++){var d=this.nodes[a];e.nodes.push({data:{id:d.name,type:d.group}})}a=0;for(b=this.links.length;a<b;a++){var d=this.links[a],f=d.value;"relation"in d&&(f=d.relation);e.edges.push({data:{source:this.nodes[d.source].name,target:this.nodes[d.target].name,relation:f}})}return e};this.getNeighbors=function(e,a){a=a||1;for(var b=[],d=this.getNodeIdsByName(e);0<a;a--){for(var f=[],l=0,k=this.links.length;l<k;l++){var g=this.links[l],
h=g.source.index,g=g.target.index;!utils.isObjInArray(d,g)&&utils.isObjInArray(d,h)?(f.push(g),b.push(this.nodes[g])):!utils.isObjInArray(d,h)&&utils.isObjInArray(d,g)&&(f.push(h),b.push(this.nodes[h]))}d=d.concat(f)}return utils.eliminateDuplicates(b)}}})(graphData);var medbookDataLoader=medbookDataLoader||{};
(function(f){f.transposeClinicalData=function(e,a){for(var b={},d=0;d<e.length;d++){var f=e[d],l=f[a],k;for(k in f)k in b||(b[k]={}),b[k][l]=f[k]}return b};f.getClinicalData=function(e,a){for(var b=utils.getResponse(e).split("\n"),d=[],n=[],l=[],k=0;k<b.length;k++){var g=b[k];utils.beginsWith(g,"#")?n.push(g):utils.beginsWith(g,"STRING")?l=g.split("\t"):d.push(g)}b=d3.tsv.parse(d.join("\n"));d=this.transposeClinicalData(b,"SAMPLE_ID");delete d.SAMPLE_ID;n=utils.getKeys(d);for(k=0;k<n.length;k++){var g=
n[k],h=d[g],m=l[k+1],p="categoric";"number"==m.toLowerCase()?p="numeric":"date"==m.toLowerCase()&&(p="date");f.loadEventBySampleData(a,g,"","clinical data",p,h)}return b};f.getMutationData=function(e,a){for(var b=utils.getResponse(e),d=d3.tsv.parse(b),b={},f=0;f<d.length;f++){var l=d[f],k=l.Hugo_Symbol,l=l.Tumor_Sample_Barcode,l=l.replace(/_/g,"-"),l=l.replace(/[A-Z]$/,"");utils.hasOwnProperty(b,k)||(b[k]={},b[k].metadata={id:k+"_mut",name:null,displayName:null,description:null,datatype:"mutation data",
allowedValues:"categoric"},b[k].data={});b[k].data[l]=!0}d=utils.getKeys(b);for(f=0;f<d.length;f++)k=b[d[f]],a.addEvent(k.metadata,k.data);return b};f.getExpressionData=function(e,a){f.getGeneBySampleData(e,a,"_mRNA","expression data","numeric")};f.getViperData=function(e,a){f.getGeneBySampleData(e,a,"_viper","viper data","numeric")};f.getGeneBySampleData=function(e,a,b,d,n){e=utils.getResponse(e);e=d3.tsv.parse(e);for(var l in e){var k=e[l],g=k[""];delete k[""];f.loadEventBySampleData(a,g,b,d,n,
k)}};f.loadEventBySampleData=function(e,a,b,d,f,l){return e.addEvent({geneSuffix:b,id:a+b,name:d+" for "+a,displayName:a,description:null,datatype:d,allowedValues:f},l)};f.mongoClinicalData=function(e,a){for(var b=0;b<e.length;b++){var d=e[b],n=null;if(utils.hasOwnProperty(d,"sample"))n=d.sample;else if(hasOwnProperty(d,"Sample"))n=d.Sample;else if(hasOwnProperty(d,"Patient ID"))n=d["Patient ID"];else if(hasOwnProperty(d,"Patient ID "))n=d["Patient ID "];else{console.log("no sample ID found in clinical doc: "+
prettyJson(d));continue}n=n.trim();if("Patient ID"!==n&&"Patient ID "!==n)for(var l=utils.getKeys(d),k=0;k<l.length;k++){var g=l[k];if(!utils.isObjInArray(["_id","sample","Sample"],g)){var h=a.getEvent(g);null==h&&(h=f.loadEventBySampleData(a,g,"","clinical data","categoric",[]));var m={};m[n]=d[g];h.data.setData(m)}}}return h};f.mongoExpressionData=function(e,a){for(var b=0;b<e.length;b++){var d=e[b],n=null;if(utils.hasOwnProperty(d,"gene"))n=d.gene;else if(utils.hasOwnProperty(d,"id"))n=d.id;else{console.log("no gene identifier found in expression doc: "+
utils.prettyJson(d));continue}var n=n.trim(),l=n+"_mRNA";utils.getKeys(d);var k=d.samples,d={},g;for(g in k)d[g]=k[g].rsem_quan_log2;l=a.getEvent(l);null==l?f.loadEventBySampleData(a,n,"_mRNA","expression data","numeric",d):l.data.setData(d)}};f.mongoExpressionData_old=function(e,a){for(var b=0;b<e.length;b++){var d=e[b],n=null;if(utils.hasOwnProperty(d,"gene"))n=d.gene;else if(utils.hasOwnProperty(d,"id"))n=d.id;else{console.log("no gene identifier found in expression doc: "+utils.prettyJson(d));
continue}for(var n=n.trim(),l=n+"_mRNA",k=utils.getKeys(d),g=0;g<k.length;g++){var h=k[g];if(!utils.isObjInArray(["_id","gene","id"],h)){var m=a.getEvent(l);null==m&&(m=f.loadEventBySampleData(a,n,"_mRNA","expression data","numeric",[]));var p={};p[h]=parseFloat(d[h]);m.data.setData(p)}}}return m};f.getSignature=function(e,a){var b=utils.getResponse(e),b=d3.tsv.parse(b),d=e.split("/").pop(),f=a.getEvent(d);null==f&&(a.addEvent({id:d,name:null,displayName:null,description:null,datatype:"expression signature",
allowedValues:"numeric",weightedGeneVector:b},[]),f=a.getEvent(d));return f};f.loadSignatureObj=function(e,a){for(var b={},d=0;d<e.length;d++){var n=e[d],l=n.id,k=n.name,n=n.val;utils.hasOwnProperty(b,k)||(b[k]={});b[k][l]=n}l=utils.getKeys(b);for(d=0;d<l.length;d++){var k=l[d],n=b[k],g;g=k.split("_v");g.pop();g=g.join("_v");g=utils.endsWith(g,"_kinase_viper")?"kinase target activity":utils.endsWith(g,"_tf_viper")||utils.beginsWith(g,"tf_viper_")?"tf target activity":"expression signature";var h=
a.getEvent(k);null==h&&(h=f.loadEventBySampleData(a,k,"",g,"numeric",{}),h.metadata.setWeightVector([],"expression data"));h.data.setData(n)}};f.loadSignatureWeightsObj=function(e,a){var b=e.name+"_v"+e.version,d;d=utils.endsWith(e.name,"_kinase_viper")?"kinase target activity":utils.endsWith(e.name,"_tf_viper")||utils.beginsWith(e.name,"tf_viper_")?"tf target activity":"expression signature";for(var n=a.getEvent(b),l=[],k=e.signature,g=utils.getKeys(k),h=0;h<g.length;h++){var m=g[h];l.push({gene:m,
weight:k[m].weight})}null==n&&(n=f.loadEventBySampleData(a,b,"",d,"numeric",[]));n.metadata.setWeightVector(l,"expression data");return n};f.loadBmegSignatureWeightsAsSamples=function(e,a){var b=utils.getKeys(e.query.weights),d=e.features,n=[],l=[],k;for(k in d)n.push({gene:k,weight:d[k]}),l.push(k);var l=utils.eliminateDuplicates(l),g=e.signatures,d={},h={},m;for(m in g){k=g[m];h[m]=k.score;var p=k.weights;k=b.slice(0);k=k.concat(utils.getKeys(p));k=utils.eliminateDuplicates(k);for(var q=0,r=k.length;q<
r;q++){var t=k[q];if(utils.isObjInArray(b,t)||utils.isObjInArray(l,t)){var v=p[t];"undefined"!==typeof v&&(utils.hasOwnProperty(d,t)||(d[t]={}),d[t][m]=v)}}}console.log("num genes:"+utils.getKeys(d).length);f.loadEventBySampleData(a,"query_score","","signature query score","numeric",h).metadata.setWeightVector(n,"signature weight");k=utils.getKeys(d);for(b=0;b<k.length;b++)t=k[b],n=t+"_weight",l=a.getEvent(n),null==l?(l=f.loadEventBySampleData(a,t,"_weight","signature weight","numeric",d[t]),l.metadata.setScoreRange(-1,
1)):console.log("loadBmegSignatureWeightsAsSamples:","existing event for: "+n)};f.loadPivotScores=function(e,a){for(var b=[],d=0;d<e.length;d++){var f=e[d],l=f.name_1,k=function(a,d,b){var e;"signature"===d?e=a+"_v"+b:"expression"===d&&(e=a);return e},l=k(l,f.datatype_1,f.version_1),g=f.name_2,g=k(g,f.datatype_2,f.version_2);b.push({eventId1:l,eventId2:g,score:f.score})}a.setPivotScores_array(null,b)}})(medbookDataLoader);var circleMapGenerator={};
(function(f){f.examplecmgParams={features:"ABTB2_mRNA APOBEC3F_mRNA APP_mRNA AR_mRNA DZIP1_mRNA EPAS1_mRNA ERG_mRNA ESR2_mRNA FGD1_mRNA FKBP9_mRNA IL6_mRNA MYOM2_mRNA NCOA1_mRNA P2RY10_mRNA PPP2R5C_mRNA PTGER3_mRNA SLC16A1_mRNA ST5_mRNA TBC1D16_mRNA TBX21_mRNA TGFB1_mRNA TGFB2_mRNA UGDH_mRNA USP20_mRNA VEGFA_mRNA ZFPM2_mRNA".split(" "),ringsList:["core_subtype","expression data","viper data"],orderFeature:["core_subtype","AR_mRNA"],sortingRing:"expression data"};f.circleMapGenerator=function(e,a){function b(a,
d,b){if(!utils.isNumerical(a))return"grey";var e=255,f=0,g=0,h=255,k=255,l=255;b=a/b;0<=a||(f=e=0,l=k=h=g=255,b=a/d);a=utils.linearInterpolation(b,h,e);f=utils.linearInterpolation(b,k,f);g=utils.linearInterpolation(b,l,g);a=utils.rangeLimit(a,0,255);f=utils.rangeLimit(f,0,255);g=utils.rangeLimit(g,0,255);return utils.rgbToHex(Math.floor(a),Math.floor(f),Math.floor(g))}function d(a,d,b,e){return d3.svg.arc().innerRadius(a).outerRadius(d).startAngle(Math.PI/180*b).endAngle(Math.PI/180*e)}this.eventAlbum=
e.fillInMissingSamples();this.cmgParams=a;this.eventStats={};this.colorMappers={};var f=this.eventAlbum.getEventIdsByType(),l;for(l in f)for(var k=f[l],g=0;g<k.length;g++){var h=k[g],m=this.eventAlbum.getEvent(h);utils.isObjInArray(["numeric"],m.metadata.allowedValues)?this.eventStats[h]=m.data.getStats():this.colorMappers[h]=d3.scale.category10()}this.getQueryFeatures=function(){return"features"in this.cmgParams?this.cmgParams.features:[]};this.getDatasetNames=function(){return this.eventAlbum.getEventIdsByType()};
this.logData=function(){console.log(this)};this.getSampleNames=function(){return this.eventAlbum.getAllSampleIds()};this.getRingData=function(a){var d=this.eventAlbum.getEvent(a);if(null==d)return null;a={};for(var d=d.data.getData(),b=0;b<d.length;b++){var e=d[b];a[e.id]=e.val}return a};this.sortSamples=function(){var a=new eventData.sortingSteps;if(utils.hasOwnProperty(this.cmgParams,"orderFeature")){var d=[].concat(this.cmgParams.orderFeature);d.reverse();for(var b=0;b<d.length;b++)a.addStep(d[b])}else a.addStep(this.getQueryFeatures()[0]);
this.sortedSamples=this.eventAlbum.multisortSamples(a)};this.sortSamples();this.generateCircleMapSvgGElem=function(a,e,f){f=f||!1;var g=this.cmgParams.ringsList,h=("undefined"===typeof e?100:e)/(g.length+1),k=h,l=360/this.sortedSamples.length;e=document.createElementNS(utils.svgNamespaceUri,"g");utils.setElemAttributes(e,{"class":"circleMapG",feature:a});e.appendChild(utils.createSvgCircleElement(0,0,k,{fill:"white"}));for(var m,n=0;n<g.length;n++){var x=g[n],w=null,w=x in this.eventAlbum.datatypeSuffixMapping?
a+this.eventAlbum.datatypeSuffixMapping[x]:x,A=document.createElementNS(utils.svgNamespaceUri,"g");utils.setElemAttributes(A,{"class":"circleMapRingG",ringName:x,dataName:w});e.appendChild(A);var C=this.getRingData(w);if("legend"===a.toLowerCase()){"undefined"===typeof m&&(m=d3.scale.category10());var D=d(k,k+h,0,360),y=document.createElementNS(utils.svgNamespaceUri,"path");utils.setElemAttributes(y,{d:D(),fill:m(w)});A.appendChild(y)}else if(null==C)D=d(k,k+h,0,360),y=document.createElementNS(utils.svgNamespaceUri,
"path"),utils.setElemAttributes(y,{d:D(),fill:"grey"}),A.appendChild(y),w=document.createElementNS(utils.svgNamespaceUri,"title"),w.innerHTML="no data",y.appendChild(w);else{this.eventAlbum.getEvent(w);var E=this.eventStats[w],B=0,F=this.colorMappers[x];this.sortedSamples.forEach(function(e,g,m){m="grey";var n=null;e in C&&(n=C[e],m=null!=E?b(n,E.min,E.max):F(n));var q=d(k,k+h,B,B+l);g=document.createElementNS(utils.svgNamespaceUri,"path");utils.setElemAttributes(g,{d:q(),fill:m,sampleName:e,score:n});
f&&(n=utils.isNumerical(n)?n.toFixed(3):n,e="sample "+e+"'s "+x+" score for "+a+" is "+n+".",m=document.createElementNS(utils.svgNamespaceUri,"title"),m.innerHTML=e,g.appendChild(m),g.onclick=function(){var a=this.parentNode,d=a.parentNode,a=a.getAttribute("ringName"),d=d.getAttribute("feature");console.log("clicked pathElem: "+a+" for "+d)});A.appendChild(g);B+=l})}k+=h}return e};this.getCircleMapDataUri=function(a){a=this.generateCircleMapSvgGElem(a,100);return"data:image/svg+xml;utf8,"+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="-100 -100 200 200">'+
a.outerHTML+"</svg>")};this.drawCircleMap=function(a,d,b,e){b=this.generateCircleMapSvgGElem(a,b||100,e||!0);e=document.createElementNS(utils.svgNamespaceUri,"svg");utils.setElemAttributes(e,{id:"circleMapSvg"+a,"class":"circleMapSvg",name:a});e.appendChild(b);utils.extractFromD3(d).appendChild(e);return e}}})(circleMapGenerator);u="undefined"===typeof u?utils:u;circleMapGraph="undefined"===typeof circleMapGraph?{}:circleMapGraph;
(function(f){var e=utils.svgNamespaceUri,a={macromoleculeTypes:"macromolecule;protein;gene;mrna;mirna;shrna;dna;transcription factor".split(";"),nucleicAcidFeatureTypes:["nucleic acid feature","promoter"],unspecifiedEntityTypes:["unspecified entity","family","abstract"],simpleChemicalTypes:["simple chemical","small molecule"],perturbingAgentTypes:["perturbing agent"],complexTypes:["complex"],selectableEntityTypes:"unspecified entity;protein;gene;mRNA;miRNA;nucleic acid feature;small molecule;perturbing agent;complex".split(";"),edgeTypeOptions:"stop adding edges;positive regulation;negative regulation;activate transcription;inhibit transcription;component of;member of".split(";"),
edgeTypeSymbols:"stop adding edges;-a>;-a|;-t>;-t|;component>;member>".split(";")},b={linkDistance:120,linkStrength:.2,friction:.8,charge:-500,gravity:.03,nodeRadius:20};f.largeScale="scale(2)";f.smallScale="scale(0.3)";f.containerDivElem=null;f.graphDataObj=null;f.circleMapGeneratorObj=null;f.circleMapMode=!1;f.svgElem=null;f.colorMapper=null;f.force=null;f.setNewCircleMapGeneratorSettings=function(a){for(var b in a)f.circleMapGeneratorObj.cmgParams[b]=a[b];f.circleMapGeneratorObj.sortSamples()};
f.build=function(a){var b=a.medbookGraphData,e=new graphData.graphData;e.readMedbookGraphData(b);var b=new eventData.OD_eventAlbum,k=[];utils.hasOwnProperty(a,"medbookExprData")&&(medbookDataLoader.mongoExpressionData(a.medbookExprData,b),k.push("expression data"));b=new circleMapGenerator.circleMapGenerator(b,{ringsList:k});f.buildCircleMapGraph(a.containerDiv,e,b,a.circleDataLoaded)};f.buildCircleMapGraph=function(a,b,e,k){f.containerDivElem=a;f.graphDataObj=b;f.circleMapGeneratorObj=e;f.circleMapMode=
k;f.setup();f.renderGraph(f.svgElem,f.force,f.graphDataObj,f.circleMapGeneratorObj,f.circleMapMode)};f.setup=function(){$.contextMenu({selector:".circleMapRingG",trigger:"right",callback:function(a,b){console.log("elem",this[0])},build:function(a,b){var d=utils.extractFromJq(a),e=d.parentNode.getAttribute("feature"),l=d.getAttribute("ringName");return{items:{title:{name:function(){return"ring: "+l+" for "+e},icon:null,disabled:!0},sep1:"---------",sort_samples:{name:function(){return"sort samples by this ring"},
icon:null,disabled:!1,callback:function(a,b){f.clearCircleMaps();var d=f.circleMapGeneratorObj.eventAlbum.getSuffixedEventId(e,l),d=d===e?l:d;f.setNewCircleMapGeneratorSettings({orderFeature:d,sortingRing:[l]});f.attachCircleMaps()}}}}}});$.contextMenu({selector:".node",trigger:"right",callback:function(a,b){console.log("elem",this[0])},build:function(a,b){var d=utils.extractFromJq(a).getElementsByTagName("svg")[0],e=d.getAttribute("name"),l=d.getAttribute("nodeType");return{items:{title:{name:function(){return l+
": "+e},icon:null,disabled:!1},sep1:"---------",toggle_size:{name:function(){return"toggle node size"},icon:null,disabled:!1,callback:function(a,b){if(f.circleMapMode){var e=d.getElementsByClassName("circleMapG");e[0].getAttribute("transform")===f.smallScale?e[0].setAttributeNS(null,"transform",f.largeScale):e[0].setAttributeNS(null,"transform",f.smallScale)}}},pin_fold:{name:"pinning",items:{toggle_pin:{name:function(){return"toggle pin this node"},icon:null,disabled:!1,callback:function(d,b){d3.select(utils.extractFromJq(a)).each(function(a,
d){a.fixed=!a.fixed})}},pin_all:{name:"pin all nodes",icon:null,disabled:!1,callback:function(a,d){d3.selectAll(".node").each(function(a,d){a.fixed=!0});f.force.stop()}},free_all:{name:"unpin all nodes",icon:null,disabled:!1,callback:function(a,d){d3.selectAll(".node").each(function(a,d){a.fixed=!1});f.force.start()}},neighbors_test:{name:"unpin neighbors",icon:null,disabled:!1,callback:function(a,d){for(var b=f.graphDataObj.getNeighbors(e,1),g=0,h=b.length;g<h;g++)b[g].fixed=!1}}}},toggle_opacity:{name:"toggle opacity",
icon:null,disabled:!1,callback:function(a,b){var e=.3==d.getAttribute("opacity")?1:.3;utils.setElemAttributes(d,{opacity:e})}}}}}});utils.removeChildElems(f.containerDivElem);var a=window.innerWidth,e=window.innerHeight;f.svgElem=d3.select(f.containerDivElem).append("svg").attr({width:a,height:e,id:"circleMaps"});var l=f.svgElem.append("defs");f.addMarkerDefs(l);f.svgElem.append("g").attr({id:"linkLayer"});f.svgElem.append("g").attr({id:"nodeLayer"});f.colorMapper=d3.scale.category10();f.force=d3.layout.force().size([a,
e]).linkDistance(b.linkDistance).linkStrength(b.linkStrength).friction(b.friction).gravity(b.gravity)};f.addMarkerDefs=function(a){var b=a.append("marker").attr({id:"Triangle",viewBox:"0 0 10 10",refX:44,refY:"5",markerUnits:"userSpaceOnUse",markerWidth:"9",markerHeight:"9",orient:"auto"});b.append("path").attr({d:"M 0 0 L 10 5 L 0 10 z"});b=a.append("marker").attr({id:"Bar",viewBox:"0 0 10 10",refX:37,refY:"5",markerUnits:"userSpaceOnUse",markerWidth:"9",markerHeight:"9",orient:"auto"});b.append("path").attr({d:"M 0 0 L 0 10 L 3 10 L 3 0 z"});
b=a.append("marker").attr({id:"Circle",viewBox:"0 0 10 10",refX:44,refY:"5",markerUnits:"userSpaceOnUse",markerWidth:"9",markerHeight:"9",orient:"auto"});b.append("circle").attr({cx:5,cy:5,r:5})};f.drawCircleMaps=function(a,b,e,k){for(var g in a)f.circleMapGeneratorObj.drawCircleMap(a[g],b,e,k)};f.clearCircleMaps=function(){d3.select("#nodeLayer").selectAll(".circleMapG").remove()};f.attachCircleMaps=function(){d3.select("#nodeLayer").selectAll(".node").selectAll(".circleMapSvg").each(function(a,
b){var e=f.circleMapGeneratorObj.generateCircleMapSvgGElem(a.name,100,!0);e.setAttributeNS(null,"transform",f.smallScale);this.appendChild(e)})};f.renderGraph=function(d,n,l,k,g){d.selectAll(".link").remove();d.selectAll(".node").remove();if(!(1>l.nodes.length)){k=d.select("#nodeLayer");var h=l.getAllNodeNames();g&&f.drawCircleMaps(h,k,100,!0);var m=d.select("#linkLayer").selectAll(".link").data(l.links).enter().append("line").attr("id",function(a,b){return"link"+b}).attr({"class":"link"}).style("stroke",
function(a){return f.colorMapper(a.relation)});m.style("marker-end",function(a,b){var d=a.relation;return"component>"===d?"url(#Circle)":utils.beginsWith(d,"-")&&utils.endsWith(d,">")?"url(#Triangle)":utils.beginsWith(d,"-")&&utils.endsWith(d,"|")?"url(#Bar)":null});m.style("stroke-width",function(a){return a.value});m.style("stroke-dasharray",function(a,b){return utils.beginsWith(a.relation,"-a")?"6,3":null});var p=function(a){var b={};utils.beginsWith(a,"-")&&utils.endsWith(a,">")?b["marker-end"]=
"url(#Triangle)":utils.beginsWith(a,"-")&&utils.endsWith(a,"|")&&(b["marker-end"]="url(#Bar)");utils.beginsWith(a,"-a")&&(b["stroke-dasharray"]="6,3");return b};m.on("mouseover",function(a,b){var d=document.getElementById("link"+b),e=p(a.relation),g="stroke-width:"+3*a.value+" ; stroke:"+f.colorMapper(a.relation),h;for(h in e)g=g+";"+h+":"+e[h];d.setAttributeNS(null,"style",g)}).on("mouseout",function(a,b){var d=document.getElementById("link"+b),e=p(a.relation),g="stroke-width:"+a.value+" ; stroke:"+
f.colorMapper(a.relation),h;for(h in e)g=g+";"+h+":"+e[h];d.setAttributeNS(null,"style",g)});var q=k.selectAll(".node").data(l.nodes).enter().append("g").attr("class",function(a,b){return"node "+a.name+" "+a.group});if(g)q.each(function(a){var b=document.getElementById("circleMapSvg"+a.name);b.setAttributeNS(null,"nodeType",a.group);b.getElementsByClassName("circleMapG")[0].setAttributeNS(null,"transform",f.smallScale)}).on("mouseover",function(a,b){var d=document.getElementById("circleMapSvg"+a.name).parentNode;
utils.pullElemToFront(d)});else q.on("mouseover",function(a,b){document.getElementsByClassName("node "+a.name+" "+a.group)[0].getElementsByClassName("sbgn")[0].setAttributeNS(null,"style","stroke-width:4;fill:"+f.colorMapper(a.group))}).on("mouseout",function(a,b){document.getElementsByClassName("node "+a.name+" "+a.group)[0].getElementsByClassName("sbgn")[0].setAttributeNS(null,"style","stroke-width:1;fill:"+f.colorMapper(a.group))});q.call(n.drag);q.append(function(d){var f=d.name;void 0===d.group&&
console.log("d",d);d=d.group.toString().toLowerCase();if(g&&0<=h.indexOf(f))return document.getElementById("circleMapSvg"+f);-1!=a.nucleicAcidFeatureTypes.indexOf(d)?(f=document.createElementNS(e,"path"),f.setAttributeNS(null,"class","sbgn"),d=utils.bottomRoundedRectSvgPath(-20,-15,40,30,10),f.setAttributeNS(null,"d",d)):-1!=a.macromoleculeTypes.indexOf(d)?(f=document.createElementNS(e,"path"),f.setAttributeNS(null,"class","sbgn"),d=utils.allRoundedRectSvgPath(-20,-15,40,30,10),f.setAttributeNS(null,
"d",d)):-1!=a.simpleChemicalTypes.indexOf(d)?(f=document.createElementNS(e,"circle"),f.setAttributeNS(null,"class","sbgn"),f.setAttributeNS(null,"r",nodeRadius)):-1!=a.complexTypes.indexOf(d)?(f=document.createElementNS(e,"path"),f.setAttributeNS(null,"class","sbgn"),d=utils.allAngledRectSvgPath(-50,-30,100,60),f.setAttributeNS(null,"d",d)):(f=document.createElementNS(e,"ellipse"),f.setAttributeNS(null,"class","sbgn"),f.setAttributeNS(null,"cx",0),f.setAttributeNS(null,"cy",0),f.setAttributeNS(null,
"rx",1.5*b.nodeRadius),f.setAttributeNS(null,"ry",.75*b.nodeRadius));f.setAttributeNS(null,"opacity",.6);f.setAttributeNS(null,"stroke","black");return f}).style("fill",function(a){return f.colorMapper(a.group)});q.append("svg:text").attr("text-anchor","middle").attr("dy","2.7em").text(function(a){return a.name});m.append("title").text(function(a){return f.graphDataObj.nodes[a.source].name+" "+a.relation+" "+f.graphDataObj.nodes[a.target].name});n.on("tick",function(){var a=parseFloat(f.svgElem.attr("width"))-
20,b=parseFloat(f.svgElem.attr("height"))-20;q.attr("transform",function(d){d.x=utils.rangeLimit(d.x,20,a);d.y=utils.rangeLimit(d.y,20,b);return"translate("+d.x+","+d.y+")"});m.attr("x1",function(a){return a.source.x}).attr("y1",function(a){return a.source.y}).attr("x2",function(a){return a.target.x}).attr("y2",function(a){return a.target.y});.03>n.alpha()&&(console.log("stop layout with alpha="+n.alpha()),d3.selectAll(".node").each(function(a,b){a.fixed=!0}),n.stop())});n.nodes(l.nodes).links(l.links);
n.start()}}})(circleMapGraph);
