// GeneExpressionSummary = new Meteor.Collection("gene_expression_summary");
// GeneExpressionSummary.attachSchema(geneExpressionSummarySchema);

// TODO: generated by a job


// // This is updated after importing new data from Wrangler
// var geneExpressionSummarySchema = new SimpleSchema([
//   studyAndCollaboration,
//   {
//     "gene_label": { type: String },
//     "study_label": { type: String },
//     "normalization": {
//       type: String,
//       allowedValues: _.pluck(normalizationSlugsAndNames, "value"),
//     },
//     "mean": { type: Number, decimal: true },
//     "variance": { type: Number, decimal: true },
//   }
// ]);
